// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptAlbumInvite = `-- name: AcceptAlbumInvite :one
UPDATE album_members
SET invite_status = 'accepted', accepted_at = now()
WHERE album_id = $1 AND user_id = $2 AND invite_status = 'pending'
RETURNING album_id, user_id, invite_status, accepted_at, left_at
`

type AcceptAlbumInviteParams struct {
	AlbumID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) AcceptAlbumInvite(ctx context.Context, arg AcceptAlbumInviteParams) (AlbumMember, error) {
	row := q.db.QueryRow(ctx, acceptAlbumInvite, arg.AlbumID, arg.UserID)
	var i AlbumMember
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.LeftAt,
	)
	return i, err
}

const activateAlbum = `-- name: ActivateAlbum :one
UPDATE albums
SET state = 'active', activated_at = now()
WHERE id = $1 AND state = 'pending'
RETURNING id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at
`

func (q *Queries) ActivateAlbum(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, activateAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.CoverStyle,
		&i.State,
		&i.ActivatedAt,
		&i.ArchiveUntil,
		&i.InviteExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const addAlbumMember = `-- name: AddAlbumMember :exec
INSERT INTO album_members (album_id, user_id, invite_status, accepted_at)
VALUES ($1, $2, $3, $4)
`

type AddAlbumMemberParams struct {
	AlbumID      pgtype.UUID
	UserID       pgtype.UUID
	InviteStatus string
	AcceptedAt   pgtype.Timestamptz
}

func (q *Queries) AddAlbumMember(ctx context.Context, arg AddAlbumMemberParams) error {
	_, err := q.db.Exec(ctx, addAlbumMember,
		arg.AlbumID,
		arg.UserID,
		arg.InviteStatus,
		arg.AcceptedAt,
	)
	return err
}

const archiveAlbum = `-- name: ArchiveAlbum :one
UPDATE albums
SET state = 'archived', archive_until = $2
WHERE id = $1 AND state = 'active'
RETURNING id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at
`

type ArchiveAlbumParams struct {
	ID           pgtype.UUID
	ArchiveUntil pgtype.Timestamptz
}

func (q *Queries) ArchiveAlbum(ctx context.Context, arg ArchiveAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, archiveAlbum, arg.ID, arg.ArchiveUntil)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.CoverStyle,
		&i.State,
		&i.ActivatedAt,
		&i.ArchiveUntil,
		&i.InviteExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveAlbumsForUser = `-- name: CountActiveAlbumsForUser :one
SELECT COUNT(*)::bigint AS count
FROM album_members am
JOIN albums a ON a.id = am.album_id
WHERE am.user_id = $1
  AND am.invite_status = 'accepted'
  AND am.left_at IS NULL
  AND a.state = 'active'
`

func (q *Queries) CountActiveAlbumsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAlbumsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveMembers = `-- name: CountActiveMembers :one
SELECT COUNT(*)::bigint AS count
FROM album_members
WHERE album_id = $1 AND invite_status = 'accepted' AND left_at IS NULL
`

func (q *Queries) CountActiveMembers(ctx context.Context, albumID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMembers, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlbumMembers = `-- name: CountAlbumMembers :one
SELECT COUNT(*)::bigint AS count
FROM album_members
WHERE album_id = $1 AND invite_status = 'accepted' AND left_at IS NULL
`

func (q *Queries) CountAlbumMembers(ctx context.Context, albumID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumMembers, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (creator_id, name, cover_style, state, invite_expires_at)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at
`

type CreateAlbumParams struct {
	CreatorID       pgtype.UUID
	Name            string
	CoverStyle      string
	InviteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.CreatorID,
		arg.Name,
		arg.CoverStyle,
		arg.InviteExpiresAt,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.CoverStyle,
		&i.State,
		&i.ActivatedAt,
		&i.ArchiveUntil,
		&i.InviteExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const declineAlbumInvite = `-- name: DeclineAlbumInvite :one
UPDATE album_members
SET invite_status = 'declined'
WHERE album_id = $1 AND user_id = $2 AND invite_status = 'pending'
RETURNING album_id, user_id, invite_status, accepted_at, left_at
`

type DeclineAlbumInviteParams struct {
	AlbumID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeclineAlbumInvite(ctx context.Context, arg DeclineAlbumInviteParams) (AlbumMember, error) {
	row := q.db.QueryRow(ctx, declineAlbumInvite, arg.AlbumID, arg.UserID)
	var i AlbumMember
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.LeftAt,
	)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.CoverStyle,
		&i.State,
		&i.ActivatedAt,
		&i.ArchiveUntil,
		&i.InviteExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAlbumMember = `-- name: GetAlbumMember :one
SELECT album_id, user_id, invite_status, accepted_at, left_at FROM album_members WHERE album_id = $1 AND user_id = $2
`

type GetAlbumMemberParams struct {
	AlbumID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetAlbumMember(ctx context.Context, arg GetAlbumMemberParams) (AlbumMember, error) {
	row := q.db.QueryRow(ctx, getAlbumMember, arg.AlbumID, arg.UserID)
	var i AlbumMember
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.LeftAt,
	)
	return i, err
}

const hardDeleteAlbum = `-- name: HardDeleteAlbum :exec
DELETE FROM albums WHERE id = $1
`

func (q *Queries) HardDeleteAlbum(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteAlbum, id)
	return err
}

const listActiveAlbumsWithCreatorPlan = `-- name: ListActiveAlbumsWithCreatorPlan :many
SELECT a.id, a.creator_id, a.name, a.cover_style, a.state, a.activated_at, a.archive_until, a.invite_expires_at, a.created_at, u.plan AS creator_plan
FROM albums a
JOIN users u ON u.id = a.creator_id
WHERE a.state = 'active'
  AND a.activated_at IS NOT NULL
ORDER BY a.activated_at
LIMIT 100
`

type ListActiveAlbumsWithCreatorPlanRow struct {
	ID              pgtype.UUID
	CreatorID       pgtype.UUID
	Name            string
	CoverStyle      string
	State           string
	ActivatedAt     pgtype.Timestamptz
	ArchiveUntil    pgtype.Timestamptz
	InviteExpiresAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	CreatorPlan     string
}

func (q *Queries) ListActiveAlbumsWithCreatorPlan(ctx context.Context) ([]ListActiveAlbumsWithCreatorPlanRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlbumsWithCreatorPlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlbumsWithCreatorPlanRow
	for rows.Next() {
		var i ListActiveAlbumsWithCreatorPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.CoverStyle,
			&i.State,
			&i.ActivatedAt,
			&i.ArchiveUntil,
			&i.InviteExpiresAt,
			&i.CreatedAt,
			&i.CreatorPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumMembers = `-- name: ListAlbumMembers :many
SELECT am.album_id, am.user_id, am.invite_status, am.accepted_at, am.left_at, u.username, u.display_name, u.avatar_media_id
FROM album_members am
JOIN users u ON u.id = am.user_id
WHERE am.album_id = $1 AND u.deleted_at IS NULL
ORDER BY am.accepted_at NULLS LAST, am.user_id
`

type ListAlbumMembersRow struct {
	AlbumID       pgtype.UUID
	UserID        pgtype.UUID
	InviteStatus  string
	AcceptedAt    pgtype.Timestamptz
	LeftAt        pgtype.Timestamptz
	Username      string
	DisplayName   string
	AvatarMediaID pgtype.UUID
}

func (q *Queries) ListAlbumMembers(ctx context.Context, albumID pgtype.UUID) ([]ListAlbumMembersRow, error) {
	rows, err := q.db.Query(ctx, listAlbumMembers, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumMembersRow
	for rows.Next() {
		var i ListAlbumMembersRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.UserID,
			&i.InviteStatus,
			&i.AcceptedAt,
			&i.LeftAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsForUser = `-- name: ListAlbumsForUser :many
SELECT a.id, a.creator_id, a.name, a.cover_style, a.state, a.activated_at, a.archive_until, a.invite_expires_at, a.created_at
FROM albums a
JOIN album_members am ON am.album_id = a.id
WHERE am.user_id = $1
  AND am.invite_status = 'accepted'
  AND am.left_at IS NULL
  AND a.state = $2
ORDER BY COALESCE(a.activated_at, a.created_at) DESC
`

type ListAlbumsForUserParams struct {
	UserID pgtype.UUID
	State  string
}

func (q *Queries) ListAlbumsForUser(ctx context.Context, arg ListAlbumsForUserParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsForUser, arg.UserID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.CoverStyle,
			&i.State,
			&i.ActivatedAt,
			&i.ArchiveUntil,
			&i.InviteExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedAlbumsPastRetention = `-- name: ListArchivedAlbumsPastRetention :many
SELECT id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at FROM albums
WHERE state = 'archived'
  AND archive_until IS NOT NULL
  AND archive_until <= now()
ORDER BY archive_until
LIMIT 100
`

func (q *Queries) ListArchivedAlbumsPastRetention(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, listArchivedAlbumsPastRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.CoverStyle,
			&i.State,
			&i.ActivatedAt,
			&i.ArchiveUntil,
			&i.InviteExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExpiredAlbums = `-- name: ListPendingExpiredAlbums :many
SELECT id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at FROM albums
WHERE state = 'pending' AND invite_expires_at <= now()
ORDER BY invite_expires_at
LIMIT 100
`

func (q *Queries) ListPendingExpiredAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, listPendingExpiredAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.CoverStyle,
			&i.State,
			&i.ActivatedAt,
			&i.ArchiveUntil,
			&i.InviteExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlbumDeleted = `-- name: MarkAlbumDeleted :one
UPDATE albums SET state = 'deleted' WHERE id = $1 RETURNING id, creator_id, name, cover_style, state, activated_at, archive_until, invite_expires_at, created_at
`

func (q *Queries) MarkAlbumDeleted(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, markAlbumDeleted, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.CoverStyle,
		&i.State,
		&i.ActivatedAt,
		&i.ArchiveUntil,
		&i.InviteExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMemberLeft = `-- name: MarkMemberLeft :one
UPDATE album_members
SET left_at = now()
WHERE album_id = $1 AND user_id = $2 AND left_at IS NULL
RETURNING album_id, user_id, invite_status, accepted_at, left_at
`

type MarkMemberLeftParams struct {
	AlbumID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) MarkMemberLeft(ctx context.Context, arg MarkMemberLeftParams) (AlbumMember, error) {
	row := q.db.QueryRow(ctx, markMemberLeft, arg.AlbumID, arg.UserID)
	var i AlbumMember
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.LeftAt,
	)
	return i, err
}
