// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capsules.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptCapsuleInvite = `-- name: AcceptCapsuleInvite :one
UPDATE capsule_members
SET invite_status = 'accepted', accepted_at = now()
WHERE capsule_id = $1 AND user_id = $2 AND invite_status = 'pending'
RETURNING capsule_id, user_id, role, invite_status, accepted_at, view_blocked, unlock_reveal_seen_at
`

type AcceptCapsuleInviteParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) AcceptCapsuleInvite(ctx context.Context, arg AcceptCapsuleInviteParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, acceptCapsuleInvite, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const activateCapsule = `-- name: ActivateCapsule :one
UPDATE capsules
SET state = 'active'
WHERE id = $1 AND state = 'pending'
RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

func (q *Queries) ActivateCapsule(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, activateCapsule, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const addCapsuleMember = `-- name: AddCapsuleMember :exec
INSERT INTO capsule_members (capsule_id, user_id, role, invite_status, accepted_at)
VALUES ($1, $2, $3, $4, $5)
`

type AddCapsuleMemberParams struct {
	CapsuleID    pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	InviteStatus string
	AcceptedAt   pgtype.Timestamptz
}

func (q *Queries) AddCapsuleMember(ctx context.Context, arg AddCapsuleMemberParams) error {
	_, err := q.db.Exec(ctx, addCapsuleMember,
		arg.CapsuleID,
		arg.UserID,
		arg.Role,
		arg.InviteStatus,
		arg.AcceptedAt,
	)
	return err
}

const addUnfreezeVote = `-- name: AddUnfreezeVote :exec
INSERT INTO capsule_unfreeze_votes (capsule_id, user_id)
VALUES ($1, $2)
ON CONFLICT (capsule_id, user_id) DO NOTHING
`

type AddUnfreezeVoteParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) AddUnfreezeVote(ctx context.Context, arg AddUnfreezeVoteParams) error {
	_, err := q.db.Exec(ctx, addUnfreezeVote, arg.CapsuleID, arg.UserID)
	return err
}

const archiveCapsule = `-- name: ArchiveCapsule :one
UPDATE capsules SET state = 'archived' WHERE id = $1 AND state = 'unlocked' RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

func (q *Queries) ArchiveCapsule(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, archiveCapsule, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const clearUnfreezeVotes = `-- name: ClearUnfreezeVotes :exec
DELETE FROM capsule_unfreeze_votes WHERE capsule_id = $1
`

func (q *Queries) ClearUnfreezeVotes(ctx context.Context, capsuleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearUnfreezeVotes, capsuleID)
	return err
}

const countAcceptedCapsuleMembers = `-- name: CountAcceptedCapsuleMembers :one
SELECT COUNT(*)::bigint AS count
FROM capsule_members
WHERE capsule_id = $1 AND invite_status = 'accepted'
`

func (q *Queries) CountAcceptedCapsuleMembers(ctx context.Context, capsuleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptedCapsuleMembers, capsuleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCapsulesForUser = `-- name: CountActiveCapsulesForUser :one
SELECT COUNT(*)::bigint AS count
FROM capsule_members cm
JOIN capsules c ON c.id = cm.capsule_id
WHERE cm.user_id = $1
  AND cm.invite_status = 'accepted'
  AND c.state IN ('pending', 'active', 'frozen')
`

func (q *Queries) CountActiveCapsulesForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCapsulesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCapsuleAcceptedMembers = `-- name: CountCapsuleAcceptedMembers :one
SELECT COUNT(*)::bigint AS count
FROM capsule_members
WHERE capsule_id = $1 AND invite_status = 'accepted'
`

func (q *Queries) CountCapsuleAcceptedMembers(ctx context.Context, capsuleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCapsuleAcceptedMembers, capsuleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCapsuleMemories = `-- name: CountCapsuleMemories :one
SELECT COUNT(*)::bigint AS count
FROM memories
WHERE container_type = 'capsule'
  AND container_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountCapsuleMemories(ctx context.Context, containerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCapsuleMemories, containerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemoriesByAuthorInCapsule = `-- name: CountMemoriesByAuthorInCapsule :one
SELECT COUNT(*)::bigint AS count
FROM memories
WHERE container_type = 'capsule'
  AND container_id = $1
  AND author_id = $2
  AND deleted_at IS NULL
`

type CountMemoriesByAuthorInCapsuleParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

func (q *Queries) CountMemoriesByAuthorInCapsule(ctx context.Context, arg CountMemoriesByAuthorInCapsuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoriesByAuthorInCapsule, arg.ContainerID, arg.AuthorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingCapsuleInvites = `-- name: CountPendingCapsuleInvites :one
SELECT COUNT(*)::bigint AS count
FROM capsule_members
WHERE capsule_id = $1 AND invite_status = 'pending'
`

func (q *Queries) CountPendingCapsuleInvites(ctx context.Context, capsuleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCapsuleInvites, capsuleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfreezeVotes = `-- name: CountUnfreezeVotes :one
SELECT COUNT(*)::bigint AS count
FROM capsule_unfreeze_votes WHERE capsule_id = $1
`

func (q *Queries) CountUnfreezeVotes(ctx context.Context, capsuleID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfreezeVotes, capsuleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCapsule = `-- name: CreateCapsule :one
INSERT INTO capsules (
    creator_id, name, description, type, state, unlock_at, invite_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

type CreateCapsuleParams struct {
	CreatorID       pgtype.UUID
	Name            string
	Description     *string
	Type            string
	State           string
	UnlockAt        pgtype.Timestamptz
	InviteExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateCapsule(ctx context.Context, arg CreateCapsuleParams) (Capsule, error) {
	row := q.db.QueryRow(ctx, createCapsule,
		arg.CreatorID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.State,
		arg.UnlockAt,
		arg.InviteExpiresAt,
	)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const declineCapsuleInvite = `-- name: DeclineCapsuleInvite :one
UPDATE capsule_members
SET invite_status = 'declined'
WHERE capsule_id = $1 AND user_id = $2 AND invite_status = 'pending'
RETURNING capsule_id, user_id, role, invite_status, accepted_at, view_blocked, unlock_reveal_seen_at
`

type DeclineCapsuleInviteParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeclineCapsuleInvite(ctx context.Context, arg DeclineCapsuleInviteParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, declineCapsuleInvite, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const demoteCapsuleAdmin = `-- name: DemoteCapsuleAdmin :exec
UPDATE capsule_members SET role = 'member'
WHERE capsule_id = $1 AND user_id = $2
`

type DemoteCapsuleAdminParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DemoteCapsuleAdmin(ctx context.Context, arg DemoteCapsuleAdminParams) error {
	_, err := q.db.Exec(ctx, demoteCapsuleAdmin, arg.CapsuleID, arg.UserID)
	return err
}

const freezeCapsule = `-- name: FreezeCapsule :one
UPDATE capsules
SET state = 'frozen', frozen_at = now(), streak_perfect = false
WHERE id = $1 AND state = 'active'
RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

func (q *Queries) FreezeCapsule(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, freezeCapsule, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const getCapsuleByID = `-- name: GetCapsuleByID :one
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at FROM capsules WHERE id = $1
`

func (q *Queries) GetCapsuleByID(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, getCapsuleByID, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const getCapsuleMember = `-- name: GetCapsuleMember :one
SELECT capsule_id, user_id, role, invite_status, accepted_at, view_blocked, unlock_reveal_seen_at FROM capsule_members WHERE capsule_id = $1 AND user_id = $2
`

type GetCapsuleMemberParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetCapsuleMember(ctx context.Context, arg GetCapsuleMemberParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, getCapsuleMember, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const getCapsuleRecapBusiestDay = `-- name: GetCapsuleRecapBusiestDay :one
SELECT
    (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $2::text)::date AS busiest_day,
    COUNT(*)::bigint AS capture_count
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY busiest_day
ORDER BY capture_count DESC, busiest_day ASC
LIMIT 1
`

type GetCapsuleRecapBusiestDayParams struct {
	ContainerID pgtype.UUID
	Tz          string
}

type GetCapsuleRecapBusiestDayRow struct {
	BusiestDay   pgtype.Date
	CaptureCount int64
}

func (q *Queries) GetCapsuleRecapBusiestDay(ctx context.Context, arg GetCapsuleRecapBusiestDayParams) (GetCapsuleRecapBusiestDayRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapBusiestDay, arg.ContainerID, arg.Tz)
	var i GetCapsuleRecapBusiestDayRow
	err := row.Scan(&i.BusiestDay, &i.CaptureCount)
	return i, err
}

const getCapsuleRecapCaptureSpan = `-- name: GetCapsuleRecapCaptureSpan :one
SELECT
    MIN(COALESCE(m.captured_at, m.created_at))::timestamptz AS first_captured_at,
    MAX(COALESCE(m.captured_at, m.created_at))::timestamptz AS last_captured_at,
    COUNT(DISTINCT m.author_id)::bigint AS contributor_count
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
`

type GetCapsuleRecapCaptureSpanRow struct {
	FirstCapturedAt  pgtype.Timestamptz
	LastCapturedAt   pgtype.Timestamptz
	ContributorCount int64
}

func (q *Queries) GetCapsuleRecapCaptureSpan(ctx context.Context, containerID pgtype.UUID) (GetCapsuleRecapCaptureSpanRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapCaptureSpan, containerID)
	var i GetCapsuleRecapCaptureSpanRow
	err := row.Scan(&i.FirstCapturedAt, &i.LastCapturedAt, &i.ContributorCount)
	return i, err
}

const getCapsuleRecapMinContributor = `-- name: GetCapsuleRecapMinContributor :one
SELECT m.author_id, u.username, u.display_name, COUNT(*)::bigint AS memory_count
FROM memories m
JOIN users u ON u.id = m.author_id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY m.author_id, u.username, u.display_name
HAVING COUNT(*) >= 1
ORDER BY memory_count ASC, m.author_id
LIMIT 1
`

type GetCapsuleRecapMinContributorRow struct {
	AuthorID    pgtype.UUID
	Username    string
	DisplayName string
	MemoryCount int64
}

func (q *Queries) GetCapsuleRecapMinContributor(ctx context.Context, containerID pgtype.UUID) (GetCapsuleRecapMinContributorRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapMinContributor, containerID)
	var i GetCapsuleRecapMinContributorRow
	err := row.Scan(
		&i.AuthorID,
		&i.Username,
		&i.DisplayName,
		&i.MemoryCount,
	)
	return i, err
}

const getCapsuleRecapMostReactedDetail = `-- name: GetCapsuleRecapMostReactedDetail :one
SELECT
    m.id,
    m.author_id,
    u.display_name,
    COUNT(r.*)::bigint AS reaction_count
FROM memories m
JOIN users u ON u.id = m.author_id
LEFT JOIN reactions r ON r.memory_id = m.id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY m.id, m.author_id, u.display_name
ORDER BY reaction_count DESC, m.id
LIMIT 1
`

type GetCapsuleRecapMostReactedDetailRow struct {
	ID            pgtype.UUID
	AuthorID      pgtype.UUID
	DisplayName   string
	ReactionCount int64
}

func (q *Queries) GetCapsuleRecapMostReactedDetail(ctx context.Context, containerID pgtype.UUID) (GetCapsuleRecapMostReactedDetailRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapMostReactedDetail, containerID)
	var i GetCapsuleRecapMostReactedDetailRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.DisplayName,
		&i.ReactionCount,
	)
	return i, err
}

const getCapsuleRecapNightOwlShare = `-- name: GetCapsuleRecapNightOwlShare :one
SELECT (
    CASE
        WHEN COUNT(*) = 0 THEN 0::float8
        ELSE (
            COUNT(*) FILTER (
                WHERE EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $2::text)) >= 22
                   OR EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $2::text)) < 5
            )::float8 / COUNT(*)::float8
        )
    END
)::float8 AS night_owl_share
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
`

type GetCapsuleRecapNightOwlShareParams struct {
	ContainerID pgtype.UUID
	Tz          string
}

// Fraction of captures between 22:00 and 04:59 inclusive in viewer timezone.
func (q *Queries) GetCapsuleRecapNightOwlShare(ctx context.Context, arg GetCapsuleRecapNightOwlShareParams) (float64, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapNightOwlShare, arg.ContainerID, arg.Tz)
	var night_owl_share float64
	err := row.Scan(&night_owl_share)
	return night_owl_share, err
}

const getCapsuleRecapPeakHour = `-- name: GetCapsuleRecapPeakHour :one
SELECT
    EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $2::text))::int AS peak_hour,
    COUNT(*)::bigint AS capture_count
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY peak_hour
ORDER BY capture_count DESC, peak_hour ASC
LIMIT 1
`

type GetCapsuleRecapPeakHourParams struct {
	ContainerID pgtype.UUID
	Tz          string
}

type GetCapsuleRecapPeakHourRow struct {
	PeakHour     int32
	CaptureCount int64
}

// Hour-of-day (0-23) in the viewer's IANA timezone with the most captures.
func (q *Queries) GetCapsuleRecapPeakHour(ctx context.Context, arg GetCapsuleRecapPeakHourParams) (GetCapsuleRecapPeakHourRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapPeakHour, arg.ContainerID, arg.Tz)
	var i GetCapsuleRecapPeakHourRow
	err := row.Scan(&i.PeakHour, &i.CaptureCount)
	return i, err
}

const getCapsuleRecapSecondContributor = `-- name: GetCapsuleRecapSecondContributor :one
SELECT m.author_id, u.username, u.display_name, COUNT(*)::bigint AS memory_count
FROM memories m
JOIN users u ON u.id = m.author_id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY m.author_id, u.username, u.display_name
ORDER BY memory_count DESC, m.author_id
OFFSET 1
LIMIT 1
`

type GetCapsuleRecapSecondContributorRow struct {
	AuthorID    pgtype.UUID
	Username    string
	DisplayName string
	MemoryCount int64
}

func (q *Queries) GetCapsuleRecapSecondContributor(ctx context.Context, containerID pgtype.UUID) (GetCapsuleRecapSecondContributorRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapSecondContributor, containerID)
	var i GetCapsuleRecapSecondContributorRow
	err := row.Scan(
		&i.AuthorID,
		&i.Username,
		&i.DisplayName,
		&i.MemoryCount,
	)
	return i, err
}

const getCapsuleRecapViewerContribution = `-- name: GetCapsuleRecapViewerContribution :one
SELECT
    COUNT(*)::bigint AS memories_taken,
    COUNT(*) FILTER (WHERE med.kind = 'photo')::bigint AS photos_taken,
    COUNT(*) FILTER (WHERE med.kind = 'video')::bigint AS videos_taken,
    COUNT(*) FILTER (WHERE m.voice_media_id IS NOT NULL)::bigint AS voice_notes_taken
FROM memories m
JOIN media med ON med.id = m.media_id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.author_id = $2
  AND m.deleted_at IS NULL
`

type GetCapsuleRecapViewerContributionParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

type GetCapsuleRecapViewerContributionRow struct {
	MemoriesTaken   int64
	PhotosTaken     int64
	VideosTaken     int64
	VoiceNotesTaken int64
}

// Memories captured by the viewing member (author_id = viewer).
func (q *Queries) GetCapsuleRecapViewerContribution(ctx context.Context, arg GetCapsuleRecapViewerContributionParams) (GetCapsuleRecapViewerContributionRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapViewerContribution, arg.ContainerID, arg.AuthorID)
	var i GetCapsuleRecapViewerContributionRow
	err := row.Scan(
		&i.MemoriesTaken,
		&i.PhotosTaken,
		&i.VideosTaken,
		&i.VoiceNotesTaken,
	)
	return i, err
}

const getCapsuleRecapViewerEngagement = `-- name: GetCapsuleRecapViewerEngagement :one
SELECT
    (
        SELECT COUNT(*)::bigint
        FROM reactions r
        JOIN memories m ON m.id = r.memory_id
        WHERE m.container_type = 'capsule'
          AND m.container_id = $1
          AND m.author_id <> $2
          AND r.user_id = $2
    ) AS reactions_on_others,
    (
        SELECT COUNT(*)::bigint
        FROM comments c
        JOIN memories m ON m.id = c.memory_id
        WHERE m.container_type = 'capsule'
          AND m.container_id = $1
          AND m.author_id <> $2
          AND c.author_id = $2
    ) AS comments_on_others
`

type GetCapsuleRecapViewerEngagementParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

type GetCapsuleRecapViewerEngagementRow struct {
	ReactionsOnOthers int64
	CommentsOnOthers  int64
}

func (q *Queries) GetCapsuleRecapViewerEngagement(ctx context.Context, arg GetCapsuleRecapViewerEngagementParams) (GetCapsuleRecapViewerEngagementRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapViewerEngagement, arg.ContainerID, arg.AuthorID)
	var i GetCapsuleRecapViewerEngagementRow
	err := row.Scan(&i.ReactionsOnOthers, &i.CommentsOnOthers)
	return i, err
}

const getCapsuleRecapViewerNightOwlShare = `-- name: GetCapsuleRecapViewerNightOwlShare :one
SELECT (
    CASE
        WHEN COUNT(*) = 0 THEN 0::float8
        ELSE (
            COUNT(*) FILTER (
                WHERE EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $3::text)) >= 22
                   OR EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $3::text)) < 5
            )::float8 / COUNT(*)::float8
        )
    END
)::float8 AS night_owl_share
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.author_id = $2
  AND m.deleted_at IS NULL
`

type GetCapsuleRecapViewerNightOwlShareParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
	Tz          string
}

func (q *Queries) GetCapsuleRecapViewerNightOwlShare(ctx context.Context, arg GetCapsuleRecapViewerNightOwlShareParams) (float64, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapViewerNightOwlShare, arg.ContainerID, arg.AuthorID, arg.Tz)
	var night_owl_share float64
	err := row.Scan(&night_owl_share)
	return night_owl_share, err
}

const getCapsuleRecapViewerPeakHour = `-- name: GetCapsuleRecapViewerPeakHour :one
SELECT
    EXTRACT(HOUR FROM (COALESCE(m.captured_at, m.created_at) AT TIME ZONE $3::text))::int AS peak_hour,
    COUNT(*)::bigint AS capture_count
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.author_id = $2
  AND m.deleted_at IS NULL
GROUP BY peak_hour
ORDER BY capture_count DESC, peak_hour ASC
LIMIT 1
`

type GetCapsuleRecapViewerPeakHourParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
	Tz          string
}

type GetCapsuleRecapViewerPeakHourRow struct {
	PeakHour     int32
	CaptureCount int64
}

func (q *Queries) GetCapsuleRecapViewerPeakHour(ctx context.Context, arg GetCapsuleRecapViewerPeakHourParams) (GetCapsuleRecapViewerPeakHourRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapViewerPeakHour, arg.ContainerID, arg.AuthorID, arg.Tz)
	var i GetCapsuleRecapViewerPeakHourRow
	err := row.Scan(&i.PeakHour, &i.CaptureCount)
	return i, err
}

const getCapsuleRecapViewerRank = `-- name: GetCapsuleRecapViewerRank :one
WITH counts AS (
    SELECT author_id, COUNT(*)::bigint AS memory_count
    FROM memories
    WHERE container_type = 'capsule'
      AND container_id = $1
      AND deleted_at IS NULL
    GROUP BY author_id
),
ranked AS (
    SELECT
        author_id,
        memory_count,
        RANK() OVER (ORDER BY memory_count DESC, author_id) AS rank,
        COUNT(*) OVER ()::bigint AS contributor_count
    FROM counts
)
SELECT rank, memory_count, contributor_count
FROM ranked
WHERE author_id = $2
`

type GetCapsuleRecapViewerRankParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

type GetCapsuleRecapViewerRankRow struct {
	Rank             int64
	MemoryCount      int64
	ContributorCount int64
}

func (q *Queries) GetCapsuleRecapViewerRank(ctx context.Context, arg GetCapsuleRecapViewerRankParams) (GetCapsuleRecapViewerRankRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleRecapViewerRank, arg.ContainerID, arg.AuthorID)
	var i GetCapsuleRecapViewerRankRow
	err := row.Scan(&i.Rank, &i.MemoryCount, &i.ContributorCount)
	return i, err
}

const getCapsuleUnlockStats = `-- name: GetCapsuleUnlockStats :one
SELECT
    COUNT(*)::bigint AS total_memories,
    COUNT(*) FILTER (WHERE med.kind = 'photo')::bigint AS photo_count,
    COUNT(*) FILTER (WHERE med.kind = 'video')::bigint AS video_count,
    COUNT(*) FILTER (WHERE m.voice_media_id IS NOT NULL)::bigint AS voice_count
FROM memories m
JOIN media med ON med.id = m.media_id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
`

type GetCapsuleUnlockStatsRow struct {
	TotalMemories int64
	PhotoCount    int64
	VideoCount    int64
	VoiceCount    int64
}

func (q *Queries) GetCapsuleUnlockStats(ctx context.Context, containerID pgtype.UUID) (GetCapsuleUnlockStatsRow, error) {
	row := q.db.QueryRow(ctx, getCapsuleUnlockStats, containerID)
	var i GetCapsuleUnlockStatsRow
	err := row.Scan(
		&i.TotalMemories,
		&i.PhotoCount,
		&i.VideoCount,
		&i.VoiceCount,
	)
	return i, err
}

const getLastCapsuleContributor = `-- name: GetLastCapsuleContributor :one
SELECT cm.user_id, u.username, u.display_name, c.last_contribution_at
FROM capsules c
JOIN capsule_members cm ON cm.capsule_id = c.id AND cm.invite_status = 'accepted'
JOIN users u ON u.id = cm.user_id
WHERE c.id = $1
  AND c.last_contribution_at IS NOT NULL
ORDER BY c.last_contribution_at DESC
LIMIT 1
`

type GetLastCapsuleContributorRow struct {
	UserID             pgtype.UUID
	Username           string
	DisplayName        string
	LastContributionAt pgtype.Timestamptz
}

func (q *Queries) GetLastCapsuleContributor(ctx context.Context, id pgtype.UUID) (GetLastCapsuleContributorRow, error) {
	row := q.db.QueryRow(ctx, getLastCapsuleContributor, id)
	var i GetLastCapsuleContributorRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.LastContributionAt,
	)
	return i, err
}

const getMemberLastCapsuleContribution = `-- name: GetMemberLastCapsuleContribution :one
SELECT captured_at FROM memories
WHERE container_type = 'capsule'
  AND container_id = $1
  AND author_id = $2
  AND deleted_at IS NULL
ORDER BY captured_at DESC
LIMIT 1
`

type GetMemberLastCapsuleContributionParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

func (q *Queries) GetMemberLastCapsuleContribution(ctx context.Context, arg GetMemberLastCapsuleContributionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getMemberLastCapsuleContribution, arg.ContainerID, arg.AuthorID)
	var captured_at pgtype.Timestamptz
	err := row.Scan(&captured_at)
	return captured_at, err
}

const getMostReactedCapsuleMemory = `-- name: GetMostReactedCapsuleMemory :one
SELECT m.id, COUNT(r.*)::bigint AS reaction_count
FROM memories m
LEFT JOIN reactions r ON r.memory_id = m.id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY m.id
ORDER BY reaction_count DESC
LIMIT 1
`

type GetMostReactedCapsuleMemoryRow struct {
	ID            pgtype.UUID
	ReactionCount int64
}

func (q *Queries) GetMostReactedCapsuleMemory(ctx context.Context, containerID pgtype.UUID) (GetMostReactedCapsuleMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMostReactedCapsuleMemory, containerID)
	var i GetMostReactedCapsuleMemoryRow
	err := row.Scan(&i.ID, &i.ReactionCount)
	return i, err
}

const getNextCapsuleAdminCandidate = `-- name: GetNextCapsuleAdminCandidate :one
SELECT cm.capsule_id, cm.user_id, cm.role, cm.invite_status, cm.accepted_at, cm.view_blocked, cm.unlock_reveal_seen_at
FROM capsule_members cm
WHERE cm.capsule_id = $1
  AND cm.user_id <> $2
  AND cm.invite_status = 'accepted'
ORDER BY cm.accepted_at NULLS LAST, cm.user_id
LIMIT 1
`

type GetNextCapsuleAdminCandidateParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetNextCapsuleAdminCandidate(ctx context.Context, arg GetNextCapsuleAdminCandidateParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, getNextCapsuleAdminCandidate, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const getStreakDay = `-- name: GetStreakDay :one
SELECT capsule_id, day, contributor_count FROM streak_days WHERE capsule_id = $1 AND day = $2
`

type GetStreakDayParams struct {
	CapsuleID pgtype.UUID
	Day       pgtype.Date
}

func (q *Queries) GetStreakDay(ctx context.Context, arg GetStreakDayParams) (StreakDay, error) {
	row := q.db.QueryRow(ctx, getStreakDay, arg.CapsuleID, arg.Day)
	var i StreakDay
	err := row.Scan(&i.CapsuleID, &i.Day, &i.ContributorCount)
	return i, err
}

const getTopCapsuleContributor = `-- name: GetTopCapsuleContributor :one
SELECT m.author_id, u.username, u.display_name, COUNT(*)::bigint AS memory_count
FROM memories m
JOIN users u ON u.id = m.author_id
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
GROUP BY m.author_id, u.username, u.display_name
ORDER BY memory_count DESC
LIMIT 1
`

type GetTopCapsuleContributorRow struct {
	AuthorID    pgtype.UUID
	Username    string
	DisplayName string
	MemoryCount int64
}

func (q *Queries) GetTopCapsuleContributor(ctx context.Context, containerID pgtype.UUID) (GetTopCapsuleContributorRow, error) {
	row := q.db.QueryRow(ctx, getTopCapsuleContributor, containerID)
	var i GetTopCapsuleContributorRow
	err := row.Scan(
		&i.AuthorID,
		&i.Username,
		&i.DisplayName,
		&i.MemoryCount,
	)
	return i, err
}

const hasStreakDay = `-- name: HasStreakDay :one
SELECT EXISTS(
    SELECT 1 FROM streak_days WHERE capsule_id = $1 AND day = $2
)::boolean AS exists
`

type HasStreakDayParams struct {
	CapsuleID pgtype.UUID
	Day       pgtype.Date
}

func (q *Queries) HasStreakDay(ctx context.Context, arg HasStreakDayParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasStreakDay, arg.CapsuleID, arg.Day)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listArchivedCapsulesPastViewable = `-- name: ListArchivedCapsulesPastViewable :many
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at FROM capsules
WHERE state = 'unlocked'
  AND viewable_until IS NOT NULL
  AND viewable_until <= now()
ORDER BY viewable_until
LIMIT 100
`

func (q *Queries) ListArchivedCapsulesPastViewable(ctx context.Context) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listArchivedCapsulesPastViewable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsuleMemberUserIDs = `-- name: ListCapsuleMemberUserIDs :many
SELECT user_id FROM capsule_members
WHERE capsule_id = $1 AND invite_status = 'accepted'
`

func (q *Queries) ListCapsuleMemberUserIDs(ctx context.Context, capsuleID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCapsuleMemberUserIDs, capsuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsuleMembers = `-- name: ListCapsuleMembers :many
SELECT cm.capsule_id, cm.user_id, cm.role, cm.invite_status, cm.accepted_at, cm.view_blocked, cm.unlock_reveal_seen_at, u.username, u.display_name, u.avatar_media_id
FROM capsule_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.capsule_id = $1 AND u.deleted_at IS NULL
ORDER BY cm.accepted_at NULLS LAST, cm.user_id
`

type ListCapsuleMembersRow struct {
	CapsuleID          pgtype.UUID
	UserID             pgtype.UUID
	Role               string
	InviteStatus       string
	AcceptedAt         pgtype.Timestamptz
	ViewBlocked        bool
	UnlockRevealSeenAt pgtype.Timestamptz
	Username           string
	DisplayName        string
	AvatarMediaID      pgtype.UUID
}

func (q *Queries) ListCapsuleMembers(ctx context.Context, capsuleID pgtype.UUID) ([]ListCapsuleMembersRow, error) {
	rows, err := q.db.Query(ctx, listCapsuleMembers, capsuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCapsuleMembersRow
	for rows.Next() {
		var i ListCapsuleMembersRow
		if err := rows.Scan(
			&i.CapsuleID,
			&i.UserID,
			&i.Role,
			&i.InviteStatus,
			&i.AcceptedAt,
			&i.ViewBlocked,
			&i.UnlockRevealSeenAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsuleMemories = `-- name: ListCapsuleMemories :many
SELECT m.id, m.container_type, m.container_id, m.author_id, m.media_id, m.voice_media_id, m.caption, m.created_at, m.deleted_at, m.captured_at,
       (SELECT COUNT(*)::bigint FROM reactions r WHERE r.memory_id = m.id) AS reaction_count,
       (SELECT COUNT(*)::bigint FROM comments c WHERE c.memory_id = m.id) AS comment_count,
       COALESCE(
         (
           SELECT array_agg(emoji)
           FROM (
             SELECT r.emoji
             FROM reactions r
             WHERE r.memory_id = m.id
             ORDER BY r.created_at DESC
             LIMIT 4
           ) recent
         ),
         ARRAY[]::text[]
       ) AS reaction_emojis
FROM memories m
WHERE m.container_type = 'capsule'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (m.captured_at, m.id) > ($2::timestamptz, $3::uuid)
  )
ORDER BY m.captured_at ASC, m.id ASC
LIMIT $4
`

type ListCapsuleMemoriesParams struct {
	ContainerID     pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageLimit       int32
}

type ListCapsuleMemoriesRow struct {
	ID             pgtype.UUID
	ContainerType  string
	ContainerID    pgtype.UUID
	AuthorID       pgtype.UUID
	MediaID        pgtype.UUID
	VoiceMediaID   pgtype.UUID
	Caption        *string
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CapturedAt     pgtype.Timestamptz
	ReactionCount  int64
	CommentCount   int64
	ReactionEmojis interface{}
}

func (q *Queries) ListCapsuleMemories(ctx context.Context, arg ListCapsuleMemoriesParams) ([]ListCapsuleMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listCapsuleMemories,
		arg.ContainerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCapsuleMemoriesRow
	for rows.Next() {
		var i ListCapsuleMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerType,
			&i.ContainerID,
			&i.AuthorID,
			&i.MediaID,
			&i.VoiceMediaID,
			&i.Caption,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.CapturedAt,
			&i.ReactionCount,
			&i.CommentCount,
			&i.ReactionEmojis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesDueUnlock = `-- name: ListCapsulesDueUnlock :many
SELECT c.id, c.creator_id, c.name, c.description, c.type, c.state, c.unlock_at, c.invite_expires_at, c.frozen_at, c.unlocked_at, c.viewable_until, c.streak_current, c.streak_perfect, c.last_contribution_at, c.freeze_warning_sent, c.created_at, c.unlock_reminder_sent_at, u.plan AS creator_plan
FROM capsules c
JOIN users u ON u.id = c.creator_id
WHERE c.state IN ('active', 'frozen')
  AND c.unlock_at <= now()
ORDER BY c.unlock_at
LIMIT 100
`

type ListCapsulesDueUnlockRow struct {
	ID                   pgtype.UUID
	CreatorID            pgtype.UUID
	Name                 string
	Description          *string
	Type                 string
	State                string
	UnlockAt             pgtype.Timestamptz
	InviteExpiresAt      pgtype.Timestamptz
	FrozenAt             pgtype.Timestamptz
	UnlockedAt           pgtype.Timestamptz
	ViewableUntil        pgtype.Timestamptz
	StreakCurrent        int32
	StreakPerfect        bool
	LastContributionAt   pgtype.Timestamptz
	FreezeWarningSent    bool
	CreatedAt            pgtype.Timestamptz
	UnlockReminderSentAt pgtype.Timestamptz
	CreatorPlan          string
}

func (q *Queries) ListCapsulesDueUnlock(ctx context.Context) ([]ListCapsulesDueUnlockRow, error) {
	rows, err := q.db.Query(ctx, listCapsulesDueUnlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCapsulesDueUnlockRow
	for rows.Next() {
		var i ListCapsulesDueUnlockRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
			&i.CreatorPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesDueUnlockReminder = `-- name: ListCapsulesDueUnlockReminder :many
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
FROM capsules
WHERE state IN ('active', 'frozen')
  AND unlock_reminder_sent_at IS NULL
  AND unlock_at > now()
  AND unlock_at <= now() + interval '10 minutes'
`

func (q *Queries) ListCapsulesDueUnlockReminder(ctx context.Context) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsulesDueUnlockReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesForUser = `-- name: ListCapsulesForUser :many
SELECT c.id, c.creator_id, c.name, c.description, c.type, c.state, c.unlock_at, c.invite_expires_at, c.frozen_at, c.unlocked_at, c.viewable_until, c.streak_current, c.streak_perfect, c.last_contribution_at, c.freeze_warning_sent, c.created_at, c.unlock_reminder_sent_at
FROM capsules c
JOIN capsule_members cm ON cm.capsule_id = c.id
WHERE cm.user_id = $1
  AND (
    ($2 = 'invites' AND cm.invite_status = 'pending' AND c.state = 'pending')
    OR (
      cm.invite_status = 'accepted'
      AND (
        ($2 = 'ongoing' AND c.state IN ('pending', 'active', 'frozen'))
        OR ($2 = 'frozen' AND c.state = 'frozen')
        OR ($2 = 'completed' AND c.state IN ('unlocked', 'archived')
            AND (c.viewable_until IS NULL OR c.viewable_until > now()))
      )
    )
  )
ORDER BY c.unlock_at ASC
`

type ListCapsulesForUserParams struct {
	UserID pgtype.UUID
	Filter interface{}
}

func (q *Queries) ListCapsulesForUser(ctx context.Context, arg ListCapsulesForUserParams) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsulesForUser, arg.UserID, arg.Filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesNeedingFreezeWarning = `-- name: ListCapsulesNeedingFreezeWarning :many
SELECT c.id, c.creator_id, c.name, c.description, c.type, c.state, c.unlock_at, c.invite_expires_at, c.frozen_at, c.unlocked_at, c.viewable_until, c.streak_current, c.streak_perfect, c.last_contribution_at, c.freeze_warning_sent, c.created_at, c.unlock_reminder_sent_at FROM capsules c
WHERE c.state = 'active'
  AND c.last_contribution_at IS NOT NULL
  AND c.last_contribution_at <= now() - interval '5 days'
  AND c.last_contribution_at > now() - interval '7 days'
  AND c.freeze_warning_sent = false
ORDER BY c.last_contribution_at
LIMIT 100
`

func (q *Queries) ListCapsulesNeedingFreezeWarning(ctx context.Context) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsulesNeedingFreezeWarning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesOwnedByUser = `-- name: ListCapsulesOwnedByUser :many
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at FROM capsules WHERE creator_id = $1 AND state NOT IN ('disintegrated', 'archived')
`

func (q *Queries) ListCapsulesOwnedByUser(ctx context.Context, creatorID pgtype.UUID) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsulesOwnedByUser, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapsulesToFreeze = `-- name: ListCapsulesToFreeze :many
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at FROM capsules
WHERE state = 'active'
  AND (
    (last_contribution_at IS NOT NULL AND last_contribution_at <= now() - interval '7 days')
    OR (last_contribution_at IS NULL AND created_at <= now() - interval '7 days')
  )
ORDER BY COALESCE(last_contribution_at, created_at)
LIMIT 100
`

func (q *Queries) ListCapsulesToFreeze(ctx context.Context) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listCapsulesToFreeze)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExpiredCapsules = `-- name: ListPendingExpiredCapsules :many
SELECT id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at FROM capsules
WHERE state = 'pending' AND invite_expires_at IS NOT NULL AND invite_expires_at <= now()
ORDER BY invite_expires_at
LIMIT 100
`

func (q *Queries) ListPendingExpiredCapsules(ctx context.Context) ([]Capsule, error) {
	rows, err := q.db.Query(ctx, listPendingExpiredCapsules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capsule
	for rows.Next() {
		var i Capsule
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.State,
			&i.UnlockAt,
			&i.InviteExpiresAt,
			&i.FrozenAt,
			&i.UnlockedAt,
			&i.ViewableUntil,
			&i.StreakCurrent,
			&i.StreakPerfect,
			&i.LastContributionAt,
			&i.FreezeWarningSent,
			&i.CreatedAt,
			&i.UnlockReminderSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineCapsuleCountdowns = `-- name: ListTimelineCapsuleCountdowns :many
SELECT c.id AS capsule_id, c.name AS capsule_name, c.unlock_at
FROM capsules c
JOIN capsule_members cm ON cm.capsule_id = c.id AND cm.user_id = $1
WHERE cm.invite_status = 'accepted'
  AND c.state IN ('active', 'frozen', 'pending')
  AND c.unlock_at >= $2
  AND c.unlock_at < $3
ORDER BY c.unlock_at
`

type ListTimelineCapsuleCountdownsParams struct {
	UserID     pgtype.UUID
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
}

type ListTimelineCapsuleCountdownsRow struct {
	CapsuleID   pgtype.UUID
	CapsuleName string
	UnlockAt    pgtype.Timestamptz
}

func (q *Queries) ListTimelineCapsuleCountdowns(ctx context.Context, arg ListTimelineCapsuleCountdownsParams) ([]ListTimelineCapsuleCountdownsRow, error) {
	rows, err := q.db.Query(ctx, listTimelineCapsuleCountdowns, arg.UserID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineCapsuleCountdownsRow
	for rows.Next() {
		var i ListTimelineCapsuleCountdownsRow
		if err := rows.Scan(&i.CapsuleID, &i.CapsuleName, &i.UnlockAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineCapsuleSealedMarkers = `-- name: ListTimelineCapsuleSealedMarkers :many
SELECT c.id AS capsule_id, c.name AS capsule_name, sd.day AS contribution_day
FROM streak_days sd
JOIN capsules c ON c.id = sd.capsule_id
JOIN capsule_members cm ON cm.capsule_id = c.id AND cm.user_id = $1
WHERE cm.invite_status = 'accepted'
  AND c.state IN ('active', 'frozen', 'pending')
  AND sd.day >= $2::date
  AND sd.day < $3::date
ORDER BY sd.day
`

type ListTimelineCapsuleSealedMarkersParams struct {
	UserID   pgtype.UUID
	StartDay pgtype.Date
	EndDay   pgtype.Date
}

type ListTimelineCapsuleSealedMarkersRow struct {
	CapsuleID       pgtype.UUID
	CapsuleName     string
	ContributionDay pgtype.Date
}

func (q *Queries) ListTimelineCapsuleSealedMarkers(ctx context.Context, arg ListTimelineCapsuleSealedMarkersParams) ([]ListTimelineCapsuleSealedMarkersRow, error) {
	rows, err := q.db.Query(ctx, listTimelineCapsuleSealedMarkers, arg.UserID, arg.StartDay, arg.EndDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineCapsuleSealedMarkersRow
	for rows.Next() {
		var i ListTimelineCapsuleSealedMarkersRow
		if err := rows.Scan(&i.CapsuleID, &i.CapsuleName, &i.ContributionDay); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineUnlockedCapsuleMemories = `-- name: ListTimelineUnlockedCapsuleMemories :many
SELECT m.id, m.container_id AS capsule_id, m.captured_at,
       med.bucket_key AS media_key, c.name AS capsule_name
FROM memories m
JOIN media med ON med.id = m.media_id
JOIN capsules c ON c.id = m.container_id
JOIN capsule_members cm ON cm.capsule_id = c.id AND cm.user_id = $1
WHERE m.container_type = 'capsule'
  AND m.deleted_at IS NULL
  AND cm.invite_status = 'accepted'
  AND cm.view_blocked = false
  AND c.state = 'unlocked'
  AND (c.viewable_until IS NULL OR c.viewable_until > now())
  AND m.captured_at >= $2
  AND m.captured_at < $3
ORDER BY m.captured_at
`

type ListTimelineUnlockedCapsuleMemoriesParams struct {
	UserID       pgtype.UUID
	CapturedAt   pgtype.Timestamptz
	CapturedAt_2 pgtype.Timestamptz
}

type ListTimelineUnlockedCapsuleMemoriesRow struct {
	ID          pgtype.UUID
	CapsuleID   pgtype.UUID
	CapturedAt  pgtype.Timestamptz
	MediaKey    string
	CapsuleName string
}

func (q *Queries) ListTimelineUnlockedCapsuleMemories(ctx context.Context, arg ListTimelineUnlockedCapsuleMemoriesParams) ([]ListTimelineUnlockedCapsuleMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listTimelineUnlockedCapsuleMemories, arg.UserID, arg.CapturedAt, arg.CapturedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineUnlockedCapsuleMemoriesRow
	for rows.Next() {
		var i ListTimelineUnlockedCapsuleMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CapsuleID,
			&i.CapturedAt,
			&i.MediaKey,
			&i.CapsuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCapsuleDisintegrated = `-- name: MarkCapsuleDisintegrated :one
UPDATE capsules SET state = 'disintegrated' WHERE id = $1 RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

func (q *Queries) MarkCapsuleDisintegrated(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, markCapsuleDisintegrated, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const markCapsuleUnlockRevealSeen = `-- name: MarkCapsuleUnlockRevealSeen :one
UPDATE capsule_members
SET unlock_reveal_seen_at = COALESCE(unlock_reveal_seen_at, now())
WHERE capsule_id = $1 AND user_id = $2 AND invite_status = 'accepted'
RETURNING capsule_id, user_id, role, invite_status, accepted_at, view_blocked, unlock_reveal_seen_at
`

type MarkCapsuleUnlockRevealSeenParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) MarkCapsuleUnlockRevealSeen(ctx context.Context, arg MarkCapsuleUnlockRevealSeenParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, markCapsuleUnlockRevealSeen, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const markFreezeWarningSent = `-- name: MarkFreezeWarningSent :exec
UPDATE capsules SET freeze_warning_sent = true WHERE id = $1
`

func (q *Queries) MarkFreezeWarningSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFreezeWarningSent, id)
	return err
}

const markUnlockReminderSent = `-- name: MarkUnlockReminderSent :execrows
UPDATE capsules
SET unlock_reminder_sent_at = now()
WHERE id = $1
  AND unlock_reminder_sent_at IS NULL
`

func (q *Queries) MarkUnlockReminderSent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markUnlockReminderSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeCapsuleMember = `-- name: RemoveCapsuleMember :exec
DELETE FROM capsule_members WHERE capsule_id = $1 AND user_id = $2
`

type RemoveCapsuleMemberParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) RemoveCapsuleMember(ctx context.Context, arg RemoveCapsuleMemberParams) error {
	_, err := q.db.Exec(ctx, removeCapsuleMember, arg.CapsuleID, arg.UserID)
	return err
}

const restampCapsuleViewableUntil = `-- name: RestampCapsuleViewableUntil :exec
UPDATE capsules
SET viewable_until = $2
WHERE id = $1 AND state = 'unlocked'
  AND (viewable_until IS NULL OR viewable_until > now())
`

type RestampCapsuleViewableUntilParams struct {
	ID            pgtype.UUID
	ViewableUntil pgtype.Timestamptz
}

func (q *Queries) RestampCapsuleViewableUntil(ctx context.Context, arg RestampCapsuleViewableUntilParams) error {
	_, err := q.db.Exec(ctx, restampCapsuleViewableUntil, arg.ID, arg.ViewableUntil)
	return err
}

const restampCreatorCapsulesViewable = `-- name: RestampCreatorCapsulesViewable :exec
UPDATE capsules c
SET viewable_until = CASE
    WHEN $2::int = -1 THEN NULL
    ELSE COALESCE(c.unlocked_at, now()) + ($2 || ' days')::interval
END
FROM users u
WHERE c.creator_id = u.id
  AND u.id = $1
  AND c.state = 'unlocked'
  AND (c.viewable_until IS NULL OR c.viewable_until > now())
`

type RestampCreatorCapsulesViewableParams struct {
	ID      pgtype.UUID
	Column2 int32
}

func (q *Queries) RestampCreatorCapsulesViewable(ctx context.Context, arg RestampCreatorCapsulesViewableParams) error {
	_, err := q.db.Exec(ctx, restampCreatorCapsulesViewable, arg.ID, arg.Column2)
	return err
}

const setAllNonAdminViewBlocked = `-- name: SetAllNonAdminViewBlocked :exec
UPDATE capsule_members
SET view_blocked = true
WHERE capsule_id = $1
  AND role <> 'admin'
  AND invite_status = 'accepted'
`

func (q *Queries) SetAllNonAdminViewBlocked(ctx context.Context, capsuleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setAllNonAdminViewBlocked, capsuleID)
	return err
}

const setCapsuleMemberViewBlocked = `-- name: SetCapsuleMemberViewBlocked :exec
UPDATE capsule_members
SET view_blocked = $3
WHERE capsule_id = $1 AND user_id = $2
`

type SetCapsuleMemberViewBlockedParams struct {
	CapsuleID   pgtype.UUID
	UserID      pgtype.UUID
	ViewBlocked bool
}

func (q *Queries) SetCapsuleMemberViewBlocked(ctx context.Context, arg SetCapsuleMemberViewBlockedParams) error {
	_, err := q.db.Exec(ctx, setCapsuleMemberViewBlocked, arg.CapsuleID, arg.UserID, arg.ViewBlocked)
	return err
}

const setCapsuleStreakPerfect = `-- name: SetCapsuleStreakPerfect :exec
UPDATE capsules SET streak_perfect = $2 WHERE id = $1
`

type SetCapsuleStreakPerfectParams struct {
	ID            pgtype.UUID
	StreakPerfect bool
}

func (q *Queries) SetCapsuleStreakPerfect(ctx context.Context, arg SetCapsuleStreakPerfectParams) error {
	_, err := q.db.Exec(ctx, setCapsuleStreakPerfect, arg.ID, arg.StreakPerfect)
	return err
}

const transferCapsuleAdmin = `-- name: TransferCapsuleAdmin :exec
UPDATE capsule_members SET role = 'admin'
WHERE capsule_id = $1 AND user_id = $2
`

type TransferCapsuleAdminParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) TransferCapsuleAdmin(ctx context.Context, arg TransferCapsuleAdminParams) error {
	_, err := q.db.Exec(ctx, transferCapsuleAdmin, arg.CapsuleID, arg.UserID)
	return err
}

const unblockCapsuleMember = `-- name: UnblockCapsuleMember :one
UPDATE capsule_members
SET view_blocked = false
WHERE capsule_id = $1 AND user_id = $2 AND view_blocked = true
RETURNING capsule_id, user_id, role, invite_status, accepted_at, view_blocked, unlock_reveal_seen_at
`

type UnblockCapsuleMemberParams struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) UnblockCapsuleMember(ctx context.Context, arg UnblockCapsuleMemberParams) (CapsuleMember, error) {
	row := q.db.QueryRow(ctx, unblockCapsuleMember, arg.CapsuleID, arg.UserID)
	var i CapsuleMember
	err := row.Scan(
		&i.CapsuleID,
		&i.UserID,
		&i.Role,
		&i.InviteStatus,
		&i.AcceptedAt,
		&i.ViewBlocked,
		&i.UnlockRevealSeenAt,
	)
	return i, err
}

const unfreezeCapsule = `-- name: UnfreezeCapsule :one
UPDATE capsules
SET state = 'active', frozen_at = NULL, streak_current = 0, freeze_warning_sent = false
WHERE id = $1 AND state = 'frozen'
RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

func (q *Queries) UnfreezeCapsule(ctx context.Context, id pgtype.UUID) (Capsule, error) {
	row := q.db.QueryRow(ctx, unfreezeCapsule, id)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const unlockCapsule = `-- name: UnlockCapsule :one
UPDATE capsules
SET state = 'unlocked', unlocked_at = now(), viewable_until = $2
WHERE id = $1 AND state IN ('active', 'frozen')
RETURNING id, creator_id, name, description, type, state, unlock_at, invite_expires_at, frozen_at, unlocked_at, viewable_until, streak_current, streak_perfect, last_contribution_at, freeze_warning_sent, created_at, unlock_reminder_sent_at
`

type UnlockCapsuleParams struct {
	ID            pgtype.UUID
	ViewableUntil pgtype.Timestamptz
}

func (q *Queries) UnlockCapsule(ctx context.Context, arg UnlockCapsuleParams) (Capsule, error) {
	row := q.db.QueryRow(ctx, unlockCapsule, arg.ID, arg.ViewableUntil)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.State,
		&i.UnlockAt,
		&i.InviteExpiresAt,
		&i.FrozenAt,
		&i.UnlockedAt,
		&i.ViewableUntil,
		&i.StreakCurrent,
		&i.StreakPerfect,
		&i.LastContributionAt,
		&i.FreezeWarningSent,
		&i.CreatedAt,
		&i.UnlockReminderSentAt,
	)
	return i, err
}

const updateCapsuleCreator = `-- name: UpdateCapsuleCreator :exec
UPDATE capsules SET creator_id = $2 WHERE id = $1
`

type UpdateCapsuleCreatorParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

func (q *Queries) UpdateCapsuleCreator(ctx context.Context, arg UpdateCapsuleCreatorParams) error {
	_, err := q.db.Exec(ctx, updateCapsuleCreator, arg.ID, arg.CreatorID)
	return err
}

const updateCapsuleLastContribution = `-- name: UpdateCapsuleLastContribution :exec
UPDATE capsules
SET last_contribution_at = $2, streak_current = $3
WHERE id = $1
`

type UpdateCapsuleLastContributionParams struct {
	ID                 pgtype.UUID
	LastContributionAt pgtype.Timestamptz
	StreakCurrent      int32
}

func (q *Queries) UpdateCapsuleLastContribution(ctx context.Context, arg UpdateCapsuleLastContributionParams) error {
	_, err := q.db.Exec(ctx, updateCapsuleLastContribution, arg.ID, arg.LastContributionAt, arg.StreakCurrent)
	return err
}

const upsertStreakDay = `-- name: UpsertStreakDay :exec
INSERT INTO streak_days (capsule_id, day, contributor_count)
VALUES ($1, $2, 1)
ON CONFLICT (capsule_id, day) DO UPDATE
SET contributor_count = streak_days.contributor_count + 1
`

type UpsertStreakDayParams struct {
	CapsuleID pgtype.UUID
	Day       pgtype.Date
}

func (q *Queries) UpsertStreakDay(ctx context.Context, arg UpsertStreakDayParams) error {
	_, err := q.db.Exec(ctx, upsertStreakDay, arg.CapsuleID, arg.Day)
	return err
}
