// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletion.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlocksForUser = `-- name: DeleteBlocksForUser :exec
DELETE FROM blocks WHERE blocker_id = $1 OR blocked_id = $1
`

func (q *Queries) DeleteBlocksForUser(ctx context.Context, blockerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlocksForUser, blockerID)
	return err
}

const deleteCapsuleMembershipsForUser = `-- name: DeleteCapsuleMembershipsForUser :exec
DELETE FROM capsule_members WHERE user_id = $1
`

func (q *Queries) DeleteCapsuleMembershipsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCapsuleMembershipsForUser, userID)
	return err
}

const deleteCommentsForUser = `-- name: DeleteCommentsForUser :exec
DELETE FROM comments WHERE author_id = $1
`

func (q *Queries) DeleteCommentsForUser(ctx context.Context, authorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentsForUser, authorID)
	return err
}

const deleteFriendshipsForUser = `-- name: DeleteFriendshipsForUser :exec
DELETE FROM friendships WHERE user_a = $1 OR user_b = $1
`

func (q *Queries) DeleteFriendshipsForUser(ctx context.Context, userA pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendshipsForUser, userA)
	return err
}

const deleteInviteLinkForUser = `-- name: DeleteInviteLinkForUser :exec
DELETE FROM invite_links WHERE user_id = $1
`

func (q *Queries) DeleteInviteLinkForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInviteLinkForUser, userID)
	return err
}

const deleteNotificationOutboxForUser = `-- name: DeleteNotificationOutboxForUser :exec
DELETE FROM notification_outbox WHERE user_id = $1
`

func (q *Queries) DeleteNotificationOutboxForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationOutboxForUser, userID)
	return err
}

const deleteNotificationPrefsForUser = `-- name: DeleteNotificationPrefsForUser :exec
DELETE FROM notification_prefs WHERE user_id = $1
`

func (q *Queries) DeleteNotificationPrefsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotificationPrefsForUser, userID)
	return err
}

const deleteReactionsForUser = `-- name: DeleteReactionsForUser :exec
DELETE FROM reactions WHERE user_id = $1
`

func (q *Queries) DeleteReactionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReactionsForUser, userID)
	return err
}

const getUserByIDIncludingDeleted = `-- name: GetUserByIDIncludingDeleted :one
SELECT id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDIncludingDeleted, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAlbumMembershipsForUser = `-- name: ListActiveAlbumMembershipsForUser :many
SELECT am.album_id, a.state
FROM album_members am
JOIN albums a ON a.id = am.album_id
WHERE am.user_id = $1
  AND am.invite_status = 'accepted'
  AND am.left_at IS NULL
  AND a.state IN ('active', 'archived', 'pending')
`

type ListActiveAlbumMembershipsForUserRow struct {
	AlbumID pgtype.UUID
	State   string
}

func (q *Queries) ListActiveAlbumMembershipsForUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveAlbumMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlbumMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAlbumMembershipsForUserRow
	for rows.Next() {
		var i ListActiveAlbumMembershipsForUserRow
		if err := rows.Scan(&i.AlbumID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthoredMemoriesWithMedia = `-- name: ListAuthoredMemoriesWithMedia :many
SELECT m.id, med.bucket_key AS media_key, vm.bucket_key AS voice_key
FROM memories m
JOIN media med ON med.id = m.media_id
LEFT JOIN media vm ON vm.id = m.voice_media_id
WHERE m.author_id = $1 AND m.deleted_at IS NULL
`

type ListAuthoredMemoriesWithMediaRow struct {
	ID       pgtype.UUID
	MediaKey string
	VoiceKey *string
}

func (q *Queries) ListAuthoredMemoriesWithMedia(ctx context.Context, authorID pgtype.UUID) ([]ListAuthoredMemoriesWithMediaRow, error) {
	rows, err := q.db.Query(ctx, listAuthoredMemoriesWithMedia, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthoredMemoriesWithMediaRow
	for rows.Next() {
		var i ListAuthoredMemoriesWithMediaRow
		if err := rows.Scan(&i.ID, &i.MediaKey, &i.VoiceKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedMediaKeys = `-- name: ListOwnedMediaKeys :many
SELECT id, bucket_key FROM media WHERE owner_id = $1
`

type ListOwnedMediaKeysRow struct {
	ID        pgtype.UUID
	BucketKey string
}

func (q *Queries) ListOwnedMediaKeys(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnedMediaKeysRow, error) {
	rows, err := q.db.Query(ctx, listOwnedMediaKeys, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedMediaKeysRow
	for rows.Next() {
		var i ListOwnedMediaKeysRow
		if err := rows.Scan(&i.ID, &i.BucketKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
