// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (user_id, kind, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, kind, status, result_key, error, created_at, completed_at
`

type CreateExportJobParams struct {
	UserID pgtype.UUID
	Kind   string
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob, arg.UserID, arg.Kind)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExportJob = `-- name: GetExportJob :one
SELECT id, user_id, kind, status, result_key, error, created_at, completed_at FROM export_jobs WHERE id = $1 AND user_id = $2
`

type GetExportJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetExportJob(ctx context.Context, arg GetExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, arg.ID, arg.UserID)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExportJobByID = `-- name: GetExportJobByID :one
SELECT id, user_id, kind, status, result_key, error, created_at, completed_at FROM export_jobs WHERE id = $1
`

func (q *Queries) GetExportJobByID(ctx context.Context, id pgtype.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJobByID, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.ResultKey,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listExportableMemories = `-- name: ListExportableMemories :many
SELECT m.id,
       m.container_type,
       m.container_id,
       m.caption,
       m.created_at,
       med.bucket_key AS media_key,
       med.kind AS media_kind,
       med.content_type,
       vm.bucket_key AS voice_key
FROM memories m
JOIN media med ON med.id = m.media_id
LEFT JOIN media vm ON vm.id = m.voice_media_id
WHERE m.deleted_at IS NULL
  AND (
    (m.container_type = 'album' AND EXISTS (
        SELECT 1 FROM album_members am
        JOIN albums a ON a.id = am.album_id
        WHERE am.album_id = m.container_id
          AND am.user_id = $1
          AND am.invite_status = 'accepted'
          AND am.left_at IS NULL
          AND a.state IN ('active', 'archived')
    ))
    OR (m.container_type = 'capsule' AND EXISTS (
        SELECT 1 FROM capsule_members cm
        JOIN capsules c ON c.id = cm.capsule_id
        WHERE cm.capsule_id = m.container_id
          AND cm.user_id = $1
          AND cm.invite_status = 'accepted'
          AND cm.view_blocked = false
          AND c.state = 'unlocked'
          AND (c.viewable_until IS NULL OR c.viewable_until > now())
    ))
  )
ORDER BY m.created_at
`

type ListExportableMemoriesRow struct {
	ID            pgtype.UUID
	ContainerType string
	ContainerID   pgtype.UUID
	Caption       *string
	CreatedAt     pgtype.Timestamptz
	MediaKey      string
	MediaKind     string
	ContentType   string
	VoiceKey      *string
}

func (q *Queries) ListExportableMemories(ctx context.Context, userID pgtype.UUID) ([]ListExportableMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listExportableMemories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportableMemoriesRow
	for rows.Next() {
		var i ListExportableMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerType,
			&i.ContainerID,
			&i.Caption,
			&i.CreatedAt,
			&i.MediaKey,
			&i.MediaKind,
			&i.ContentType,
			&i.VoiceKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExportJobs = `-- name: ListPendingExportJobs :many
SELECT id, user_id, kind, status, result_key, error, created_at, completed_at FROM export_jobs
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingExportJobs(ctx context.Context, limit int32) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listPendingExportJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportJob
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.ResultKey,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportJobFailed = `-- name: MarkExportJobFailed :exec
UPDATE export_jobs
SET status = 'failed', error = $2, completed_at = now()
WHERE id = $1
`

type MarkExportJobFailedParams struct {
	ID    pgtype.UUID
	Error *string
}

func (q *Queries) MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) error {
	_, err := q.db.Exec(ctx, markExportJobFailed, arg.ID, arg.Error)
	return err
}

const markExportJobProcessing = `-- name: MarkExportJobProcessing :execrows
UPDATE export_jobs SET status = 'processing' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkExportJobProcessing(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markExportJobProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markExportJobReady = `-- name: MarkExportJobReady :exec
UPDATE export_jobs
SET status = 'ready', result_key = $2, completed_at = now()
WHERE id = $1
`

type MarkExportJobReadyParams struct {
	ID        pgtype.UUID
	ResultKey *string
}

func (q *Queries) MarkExportJobReady(ctx context.Context, arg MarkExportJobReadyParams) error {
	_, err := q.db.Exec(ctx, markExportJobReady, arg.ID, arg.ResultKey)
	return err
}
