// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendship = `-- name: AcceptFriendship :one
UPDATE friendships
SET status = 'accepted'
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
  AND status = 'pending'
  AND requested_by = $2
RETURNING user_a, user_b, status, requested_by, created_at
`

type AcceptFriendshipParams struct {
	Recipient pgtype.UUID
	Requester pgtype.UUID
}

func (q *Queries) AcceptFriendship(ctx context.Context, arg AcceptFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendship, arg.Recipient, arg.Requester)
	var i Friendship
	err := row.Scan(
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE user_a = LEAST($1::uuid, $2::uuid)
      AND user_b = GREATEST($1::uuid, $2::uuid)
      AND status = 'accepted'
) AS friends
`

type AreFriendsParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.UserA, arg.UserB)
	var friends bool
	err := row.Scan(&friends)
	return friends, err
}

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateBlockParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_a, user_b, status, requested_by)
VALUES (
    LEAST($1::uuid, $2::uuid),
    GREATEST($1::uuid, $2::uuid),
    'pending',
    $3
)
RETURNING user_a, user_b, status, requested_by, created_at
`

type CreateFriendshipParams struct {
	UserA       pgtype.UUID
	UserB       pgtype.UUID
	RequestedBy pgtype.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserA, arg.UserB, arg.RequestedBy)
	var i Friendship
	err := row.Scan(
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createInviteLink = `-- name: CreateInviteLink :one
INSERT INTO invite_links (token, user_id) VALUES ($1, $2) RETURNING token, user_id, created_at
`

type CreateInviteLinkParams struct {
	Token  string
	UserID pgtype.UUID
}

func (q *Queries) CreateInviteLink(ctx context.Context, arg CreateInviteLinkParams) (InviteLink, error) {
	row := q.db.QueryRow(ctx, createInviteLink, arg.Token, arg.UserID)
	var i InviteLink
	err := row.Scan(&i.Token, &i.UserID, &i.CreatedAt)
	return i, err
}

const deleteAcceptedFriendship = `-- name: DeleteAcceptedFriendship :execrows
DELETE FROM friendships
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
  AND status = 'accepted'
`

type DeleteAcceptedFriendshipParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) DeleteAcceptedFriendship(ctx context.Context, arg DeleteAcceptedFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcceptedFriendship, arg.UserA, arg.UserB)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
`

type DeleteFriendshipParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserA, arg.UserB)
	return err
}

const deleteIncomingFriendRequest = `-- name: DeleteIncomingFriendRequest :execrows
DELETE FROM friendships
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
  AND status = 'pending'
  AND requested_by = $2
`

type DeleteIncomingFriendRequestParams struct {
	Recipient pgtype.UUID
	Requester pgtype.UUID
}

func (q *Queries) DeleteIncomingFriendRequest(ctx context.Context, arg DeleteIncomingFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncomingFriendRequest, arg.Recipient, arg.Requester)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOutgoingFriendRequest = `-- name: DeleteOutgoingFriendRequest :execrows
DELETE FROM friendships
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
  AND status = 'pending'
  AND requested_by = $1
`

type DeleteOutgoingFriendRequestParams struct {
	Requester pgtype.UUID
	Target    pgtype.UUID
}

func (q *Queries) DeleteOutgoingFriendRequest(ctx context.Context, arg DeleteOutgoingFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutgoingFriendRequest, arg.Requester, arg.Target)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT user_a, user_b, status, requested_by, created_at FROM friendships
WHERE user_a = LEAST($1::uuid, $2::uuid)
  AND user_b = GREATEST($1::uuid, $2::uuid)
`

type GetFriendshipParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserA, arg.UserB)
	var i Friendship
	err := row.Scan(
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.RequestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteLinkByToken = `-- name: GetInviteLinkByToken :one
SELECT token, user_id, created_at FROM invite_links WHERE token = $1
`

func (q *Queries) GetInviteLinkByToken(ctx context.Context, token string) (InviteLink, error) {
	row := q.db.QueryRow(ctx, getInviteLinkByToken, token)
	var i InviteLink
	err := row.Scan(&i.Token, &i.UserID, &i.CreatedAt)
	return i, err
}

const getInviteLinkByUser = `-- name: GetInviteLinkByUser :one
SELECT token, user_id, created_at FROM invite_links WHERE user_id = $1
`

func (q *Queries) GetInviteLinkByUser(ctx context.Context, userID pgtype.UUID) (InviteLink, error) {
	row := q.db.QueryRow(ctx, getInviteLinkByUser, userID)
	var i InviteLink
	err := row.Scan(&i.Token, &i.UserID, &i.CreatedAt)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isBlockedEitherDirection = `-- name: IsBlockedEitherDirection :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
) AS blocked
`

type IsBlockedEitherDirectionParams struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
}

func (q *Queries) IsBlockedEitherDirection(ctx context.Context, arg IsBlockedEitherDirectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherDirection, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listAcceptedFriends = `-- name: ListAcceptedFriends :many
SELECT u.id, u.email, u.username, u.display_name, u.password_hash, u.avatar_media_id, u.timezone, u.plan, u.plan_expires_at, u.created_at, u.deleted_at
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.user_a = $1 THEN f.user_b ELSE f.user_a END
WHERE (f.user_a = $1 OR f.user_b = $1)
  AND f.status = 'accepted'
  AND u.deleted_at IS NULL
ORDER BY u.display_name, u.username
`

func (q *Queries) ListAcceptedFriends(ctx context.Context, userA pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriends, userA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.AvatarMediaID,
			&i.Timezone,
			&i.Plan,
			&i.PlanExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT u.id, u.email, u.username, u.display_name, u.password_hash, u.avatar_media_id, u.timezone, u.plan, u.plan_expires_at, u.created_at, u.deleted_at
FROM friendships f
JOIN users u ON u.id = f.requested_by
WHERE (f.user_a = $1 OR f.user_b = $1)
  AND f.status = 'pending'
  AND f.requested_by <> $1
  AND u.deleted_at IS NULL
ORDER BY f.created_at DESC
`

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, userA pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, userA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.AvatarMediaID,
			&i.Timezone,
			&i.Plan,
			&i.PlanExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT u.id, u.email, u.username, u.display_name, u.password_hash, u.avatar_media_id, u.timezone, u.plan, u.plan_expires_at, u.created_at, u.deleted_at
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.user_a = $1 THEN f.user_b ELSE f.user_a END
WHERE (f.user_a = $1 OR f.user_b = $1)
  AND f.status = 'pending'
  AND f.requested_by = $1
  AND u.deleted_at IS NULL
ORDER BY f.created_at DESC
`

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, userA pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, userA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.AvatarMediaID,
			&i.Timezone,
			&i.Plan,
			&i.PlanExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAcceptedFriends = `-- name: SearchAcceptedFriends :many
SELECT u.id, u.email, u.username, u.display_name, u.password_hash, u.avatar_media_id, u.timezone, u.plan, u.plan_expires_at, u.created_at, u.deleted_at
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.user_a = $1 THEN f.user_b ELSE f.user_a END
WHERE (f.user_a = $1 OR f.user_b = $1)
  AND f.status = 'accepted'
  AND u.deleted_at IS NULL
  AND (u.username ILIKE '%' || $2 || '%' OR u.display_name ILIKE '%' || $2 || '%')
ORDER BY u.display_name, u.username
`

type SearchAcceptedFriendsParams struct {
	UserA pgtype.UUID
	Query *string
}

func (q *Queries) SearchAcceptedFriends(ctx context.Context, arg SearchAcceptedFriendsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchAcceptedFriends, arg.UserA, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.AvatarMediaID,
			&i.Timezone,
			&i.Plan,
			&i.PlanExpiresAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
