// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (owner_id, kind, bucket_key, content_type, duration_ms, byte_size)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, kind, bucket_key, content_type, duration_ms, width, height, byte_size, status, created_at, thumb_bucket_key
`

type CreateMediaParams struct {
	OwnerID     pgtype.UUID
	Kind        string
	BucketKey   string
	ContentType string
	DurationMs  *int32
	ByteSize    *int64
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.OwnerID,
		arg.Kind,
		arg.BucketKey,
		arg.ContentType,
		arg.DurationMs,
		arg.ByteSize,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.BucketKey,
		&i.ContentType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbBucketKey,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, owner_id, kind, bucket_key, content_type, duration_ms, width, height, byte_size, status, created_at, thumb_bucket_key FROM media WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.BucketKey,
		&i.ContentType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbBucketKey,
	)
	return i, err
}

const listExpiredPendingMedia = `-- name: ListExpiredPendingMedia :many
SELECT id, owner_id, kind, bucket_key, content_type, duration_ms, width, height, byte_size, status, created_at, thumb_bucket_key FROM media
WHERE status = 'pending' AND created_at < $1
LIMIT 500
`

func (q *Queries) ListExpiredPendingMedia(ctx context.Context, createdAt pgtype.Timestamptz) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingMedia, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.BucketKey,
			&i.ContentType,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.ByteSize,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbBucketKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaReady = `-- name: MarkMediaReady :one
UPDATE media
SET status = 'ready', byte_size = $2, width = $3, height = $4, thumb_bucket_key = $5
WHERE id = $1 AND status = 'pending'
RETURNING id, owner_id, kind, bucket_key, content_type, duration_ms, width, height, byte_size, status, created_at, thumb_bucket_key
`

type MarkMediaReadyParams struct {
	ID             pgtype.UUID
	ByteSize       *int64
	Width          *int32
	Height         *int32
	ThumbBucketKey *string
}

func (q *Queries) MarkMediaReady(ctx context.Context, arg MarkMediaReadyParams) (Medium, error) {
	row := q.db.QueryRow(ctx, markMediaReady,
		arg.ID,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.ThumbBucketKey,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.BucketKey,
		&i.ContentType,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.ByteSize,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbBucketKey,
	)
	return i, err
}

const setUserAvatar = `-- name: SetUserAvatar :exec
UPDATE users SET avatar_media_id = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetUserAvatarParams struct {
	ID            pgtype.UUID
	AvatarMediaID pgtype.UUID
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) error {
	_, err := q.db.Exec(ctx, setUserAvatar, arg.ID, arg.AvatarMediaID)
	return err
}
