// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlbumMemories = `-- name: CountAlbumMemories :one
SELECT COUNT(*)::bigint AS count
FROM memories
WHERE container_type = 'album'
  AND container_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountAlbumMemories(ctx context.Context, containerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumMemories, containerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMemoriesByAuthorInAlbum = `-- name: CountMemoriesByAuthorInAlbum :one
SELECT COUNT(*)::bigint AS count
FROM memories
WHERE container_type = 'album'
  AND container_id = $1
  AND author_id = $2
  AND deleted_at IS NULL
`

type CountMemoriesByAuthorInAlbumParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

func (q *Queries) CountMemoriesByAuthorInAlbum(ctx context.Context, arg CountMemoriesByAuthorInAlbumParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoriesByAuthorInAlbum, arg.ContainerID, arg.AuthorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (memory_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, memory_id, author_id, body, created_at
`

type CreateCommentParams struct {
	MemoryID pgtype.UUID
	AuthorID pgtype.UUID
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.MemoryID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (container_type, container_id, author_id, media_id, voice_media_id, caption)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, container_type, container_id, author_id, media_id, voice_media_id, caption, created_at, deleted_at
`

type CreateMemoryParams struct {
	ContainerType string
	ContainerID   pgtype.UUID
	AuthorID      pgtype.UUID
	MediaID       pgtype.UUID
	VoiceMediaID  pgtype.UUID
	Caption       *string
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.ContainerType,
		arg.ContainerID,
		arg.AuthorID,
		arg.MediaID,
		arg.VoiceMediaID,
		arg.Caption,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.ContainerType,
		&i.ContainerID,
		&i.AuthorID,
		&i.MediaID,
		&i.VoiceMediaID,
		&i.Caption,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = $1 AND author_id = $2 AND memory_id = $3
`

type DeleteCommentParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
	MemoryID pgtype.UUID
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.AuthorID, arg.MemoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReaction = `-- name: DeleteReaction :execrows
DELETE FROM reactions WHERE memory_id = $1 AND user_id = $2
`

type DeleteReactionParams struct {
	MemoryID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReaction, arg.MemoryID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, memory_id, author_id, body, created_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getMemoryByID = `-- name: GetMemoryByID :one
SELECT id, container_type, container_id, author_id, media_id, voice_media_id, caption, created_at, deleted_at FROM memories WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMemoryByID(ctx context.Context, id pgtype.UUID) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByID, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.ContainerType,
		&i.ContainerID,
		&i.AuthorID,
		&i.MediaID,
		&i.VoiceMediaID,
		&i.Caption,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteMemory = `-- name: HardDeleteMemory :exec
DELETE FROM memories WHERE id = $1
`

func (q *Queries) HardDeleteMemory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteMemory, id)
	return err
}

const listAlbumMemories = `-- name: ListAlbumMemories :many
SELECT m.id, m.container_type, m.container_id, m.author_id, m.media_id, m.voice_media_id, m.caption, m.created_at, m.deleted_at,
       (SELECT COUNT(*)::bigint FROM reactions r WHERE r.memory_id = m.id) AS reaction_count,
       (SELECT COUNT(*)::bigint FROM comments c WHERE c.memory_id = m.id) AS comment_count
FROM memories m
WHERE m.container_type = 'album'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
  AND (
    $2::timestamptz IS NULL
    OR (m.created_at, m.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListAlbumMemoriesParams struct {
	ContainerID     pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageLimit       int32
}

type ListAlbumMemoriesRow struct {
	ID            pgtype.UUID
	ContainerType string
	ContainerID   pgtype.UUID
	AuthorID      pgtype.UUID
	MediaID       pgtype.UUID
	VoiceMediaID  pgtype.UUID
	Caption       *string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	ReactionCount int64
	CommentCount  int64
}

func (q *Queries) ListAlbumMemories(ctx context.Context, arg ListAlbumMemoriesParams) ([]ListAlbumMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listAlbumMemories,
		arg.ContainerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumMemoriesRow
	for rows.Next() {
		var i ListAlbumMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerType,
			&i.ContainerID,
			&i.AuthorID,
			&i.MediaID,
			&i.VoiceMediaID,
			&i.Caption,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ReactionCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumMemoryMediaKeys = `-- name: ListAlbumMemoryMediaKeys :many
SELECT m.id, med.bucket_key AS media_key, vm.bucket_key AS voice_key
FROM memories m
JOIN media med ON med.id = m.media_id
LEFT JOIN media vm ON vm.id = m.voice_media_id
WHERE m.container_type = 'album'
  AND m.container_id = $1
  AND m.deleted_at IS NULL
`

type ListAlbumMemoryMediaKeysRow struct {
	ID       pgtype.UUID
	MediaKey string
	VoiceKey *string
}

func (q *Queries) ListAlbumMemoryMediaKeys(ctx context.Context, containerID pgtype.UUID) ([]ListAlbumMemoryMediaKeysRow, error) {
	rows, err := q.db.Query(ctx, listAlbumMemoryMediaKeys, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumMemoryMediaKeysRow
	for rows.Next() {
		var i ListAlbumMemoryMediaKeysRow
		if err := rows.Scan(&i.ID, &i.MediaKey, &i.VoiceKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentAuthorsExcept = `-- name: ListCommentAuthorsExcept :many
SELECT DISTINCT author_id FROM comments
WHERE memory_id = $1 AND author_id <> $2
`

type ListCommentAuthorsExceptParams struct {
	MemoryID pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) ListCommentAuthorsExcept(ctx context.Context, arg ListCommentAuthorsExceptParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCommentAuthorsExcept, arg.MemoryID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var author_id pgtype.UUID
		if err := rows.Scan(&author_id); err != nil {
			return nil, err
		}
		items = append(items, author_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.memory_id, c.author_id, c.body, c.created_at, u.username, u.display_name
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.memory_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (c.created_at, c.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4
`

type ListCommentsParams struct {
	MemoryID        pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageLimit       int32
}

type ListCommentsRow struct {
	ID          pgtype.UUID
	MemoryID    pgtype.UUID
	AuthorID    pgtype.UUID
	Body        string
	CreatedAt   pgtype.Timestamptz
	Username    string
	DisplayName string
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments,
		arg.MemoryID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByAuthorInAlbum = `-- name: ListMemoriesByAuthorInAlbum :many
SELECT m.id, m.container_type, m.container_id, m.author_id, m.media_id, m.voice_media_id, m.caption, m.created_at, m.deleted_at, med.bucket_key AS media_key, vm.bucket_key AS voice_key
FROM memories m
JOIN media med ON med.id = m.media_id
LEFT JOIN media vm ON vm.id = m.voice_media_id
WHERE m.container_type = 'album'
  AND m.container_id = $1
  AND m.author_id = $2
  AND m.deleted_at IS NULL
`

type ListMemoriesByAuthorInAlbumParams struct {
	ContainerID pgtype.UUID
	AuthorID    pgtype.UUID
}

type ListMemoriesByAuthorInAlbumRow struct {
	ID            pgtype.UUID
	ContainerType string
	ContainerID   pgtype.UUID
	AuthorID      pgtype.UUID
	MediaID       pgtype.UUID
	VoiceMediaID  pgtype.UUID
	Caption       *string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	MediaKey      string
	VoiceKey      *string
}

func (q *Queries) ListMemoriesByAuthorInAlbum(ctx context.Context, arg ListMemoriesByAuthorInAlbumParams) ([]ListMemoriesByAuthorInAlbumRow, error) {
	rows, err := q.db.Query(ctx, listMemoriesByAuthorInAlbum, arg.ContainerID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoriesByAuthorInAlbumRow
	for rows.Next() {
		var i ListMemoriesByAuthorInAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerType,
			&i.ContainerID,
			&i.AuthorID,
			&i.MediaID,
			&i.VoiceMediaID,
			&i.Caption,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.MediaKey,
			&i.VoiceKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineAlbumMemories = `-- name: ListTimelineAlbumMemories :many
SELECT m.id, m.container_id AS album_id, m.created_at,
       med.bucket_key AS media_key, a.name AS album_name
FROM memories m
JOIN media med ON med.id = m.media_id
JOIN albums a ON a.id = m.container_id
JOIN album_members am ON am.album_id = a.id AND am.user_id = $1
WHERE m.container_type = 'album'
  AND m.deleted_at IS NULL
  AND am.invite_status = 'accepted'
  AND am.left_at IS NULL
  AND a.state IN ('active', 'archived')
  AND m.created_at >= $2
  AND m.created_at < $3
ORDER BY m.created_at
`

type ListTimelineAlbumMemoriesParams struct {
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type ListTimelineAlbumMemoriesRow struct {
	ID        pgtype.UUID
	AlbumID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
	MediaKey  string
	AlbumName string
}

func (q *Queries) ListTimelineAlbumMemories(ctx context.Context, arg ListTimelineAlbumMemoriesParams) ([]ListTimelineAlbumMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listTimelineAlbumMemories, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineAlbumMemoriesRow
	for rows.Next() {
		var i ListTimelineAlbumMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.CreatedAt,
			&i.MediaKey,
			&i.AlbumName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemory = `-- name: SoftDeleteMemory :exec
UPDATE memories SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteMemory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMemory, id)
	return err
}

const upsertReaction = `-- name: UpsertReaction :one
INSERT INTO reactions (memory_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (memory_id, user_id) DO UPDATE SET emoji = EXCLUDED.emoji, created_at = now()
RETURNING memory_id, user_id, emoji, created_at
`

type UpsertReactionParams struct {
	MemoryID pgtype.UUID
	UserID   pgtype.UUID
	Emoji    string
}

func (q *Queries) UpsertReaction(ctx context.Context, arg UpsertReactionParams) (Reaction, error) {
	row := q.db.QueryRow(ctx, upsertReaction, arg.MemoryID, arg.UserID, arg.Emoji)
	var i Reaction
	err := row.Scan(
		&i.MemoryID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}
