// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID              pgtype.UUID
	CreatorID       pgtype.UUID
	Name            string
	CoverStyle      string
	State           string
	ActivatedAt     pgtype.Timestamptz
	ArchiveUntil    pgtype.Timestamptz
	InviteExpiresAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type AlbumMember struct {
	AlbumID      pgtype.UUID
	UserID       pgtype.UUID
	InviteStatus string
	AcceptedAt   pgtype.Timestamptz
	LeftAt       pgtype.Timestamptz
}

type Block struct {
	BlockerID pgtype.UUID
	BlockedID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Capsule struct {
	ID                 pgtype.UUID
	CreatorID          pgtype.UUID
	Name               string
	Description        *string
	Type               string
	State              string
	UnlockAt           pgtype.Timestamptz
	InviteExpiresAt    pgtype.Timestamptz
	FrozenAt           pgtype.Timestamptz
	UnlockedAt         pgtype.Timestamptz
	ViewableUntil      pgtype.Timestamptz
	StreakCurrent      int32
	StreakPerfect      bool
	LastContributionAt pgtype.Timestamptz
	FreezeWarningSent  bool
	CreatedAt          pgtype.Timestamptz
}

type CapsuleMember struct {
	CapsuleID    pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	InviteStatus string
	AcceptedAt   pgtype.Timestamptz
	ViewBlocked  bool
}

type CapsuleUnfreezeVote struct {
	CapsuleID pgtype.UUID
	UserID    pgtype.UUID
	VotedAt   pgtype.Timestamptz
}

type Comment struct {
	ID        pgtype.UUID
	MemoryID  pgtype.UUID
	AuthorID  pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type ExportJob struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Kind        string
	Status      string
	ResultKey   *string
	Error       *string
	CreatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type Friendship struct {
	UserA       pgtype.UUID
	UserB       pgtype.UUID
	Status      string
	RequestedBy pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type InviteLink struct {
	Token     string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Medium struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Kind           string
	BucketKey      string
	ContentType    string
	DurationMs     *int32
	Width          *int32
	Height         *int32
	ByteSize       *int64
	Status         string
	CreatedAt      pgtype.Timestamptz
	ThumbBucketKey *string
}

type Memory struct {
	ID            pgtype.UUID
	ContainerType string
	ContainerID   pgtype.UUID
	AuthorID      pgtype.UUID
	MediaID       pgtype.UUID
	VoiceMediaID  pgtype.UUID
	Caption       *string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type NotificationOutbox struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Category     string
	Title        string
	Body         string
	Data         json.RawMessage
	BatchKey     *string
	DeliverAfter pgtype.Timestamptz
	SentAt       pgtype.Timestamptz
	ReadAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type NotificationPref struct {
	UserID   pgtype.UUID
	Category string
	Enabled  bool
}

type OtpCode struct {
	ID         pgtype.UUID
	Email      string
	CodeHash   string
	Purpose    string
	Attempts   int32
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PushToken struct {
	UserID       pgtype.UUID
	ExpoToken    string
	Platform     string
	UpdatedAt    pgtype.Timestamptz
	WidgetPushAt pgtype.Timestamptz
}

type Reaction struct {
	MemoryID  pgtype.UUID
	UserID    pgtype.UUID
	Emoji     string
	CreatedAt pgtype.Timestamptz
}

type RetiredUsername struct {
	Username  string
	RetiredAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	DeviceName       string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}

type StreakDay struct {
	CapsuleID        pgtype.UUID
	Day              pgtype.Date
	ContributorCount int32
}

type SubscriptionEvent struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	RevenuecatEventID string
	EventType         string
	Plan              string
	Raw               json.RawMessage
	CreatedAt         pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Username      string
	DisplayName   string
	PasswordHash  string
	AvatarMediaID pgtype.UUID
	Timezone      string
	Plan          string
	PlanExpiresAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}
