// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceUnlockNotificationsForUser = `-- name: AdvanceUnlockNotificationsForUser :exec
UPDATE notification_outbox
SET deliver_after = now()
WHERE user_id = $1
  AND category = 'capsule_unlock'
  AND sent_at IS NULL
  AND deliver_after > now()
  AND data->>'type' = 'capsule_unlocked'
`

// Only pull forward the actual unlock alert; leave unlock_soon reminders on schedule.
func (q *Queries) AdvanceUnlockNotificationsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, advanceUnlockNotificationsForUser, userID)
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint
FROM notification_outbox
WHERE user_id = $1
  AND sent_at IS NOT NULL
  AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOutbox = `-- name: CreateOutbox :one
INSERT INTO notification_outbox (user_id, category, title, body, data, batch_key, deliver_after)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7::timestamptz, now()))
RETURNING id, user_id, category, title, body, data, batch_key, deliver_after, sent_at, read_at, created_at
`

type CreateOutboxParams struct {
	UserID       pgtype.UUID
	Category     string
	Title        string
	Body         string
	Data         json.RawMessage
	BatchKey     *string
	DeliverAfter pgtype.Timestamptz
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, createOutbox,
		arg.UserID,
		arg.Category,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.BatchKey,
		arg.DeliverAfter,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.BatchKey,
		&i.DeliverAfter,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationForUser = `-- name: DeleteNotificationForUser :execrows
DELETE FROM notification_outbox
WHERE id = $1
  AND user_id = $2
  AND sent_at IS NOT NULL
`

type DeleteNotificationForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteNotificationForUser(ctx context.Context, arg DeleteNotificationForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOutboxRows = `-- name: DeleteOutboxRows :exec
DELETE FROM notification_outbox
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteOutboxRows(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutboxRows, dollar_1)
	return err
}

const getLastBatchSentAt = `-- name: GetLastBatchSentAt :one
SELECT max(sent_at)::timestamptz AS sent_at
FROM notification_outbox
WHERE batch_key = $1
  AND sent_at IS NOT NULL
`

func (q *Queries) GetLastBatchSentAt(ctx context.Context, batchKey *string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastBatchSentAt, batchKey)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :many
SELECT category, enabled
FROM notification_prefs
WHERE user_id = $1
`

type GetNotificationPrefsRow struct {
	Category string
	Enabled  bool
}

func (q *Queries) GetNotificationPrefs(ctx context.Context, userID pgtype.UUID) ([]GetNotificationPrefsRow, error) {
	rows, err := q.db.Query(ctx, getNotificationPrefs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationPrefsRow
	for rows.Next() {
		var i GetNotificationPrefsRow
		if err := rows.Scan(&i.Category, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingBatchMinDeliverAfter = `-- name: GetPendingBatchMinDeliverAfter :one
SELECT min(deliver_after)::timestamptz AS deliver_after
FROM notification_outbox
WHERE batch_key = $1
  AND sent_at IS NULL
`

func (q *Queries) GetPendingBatchMinDeliverAfter(ctx context.Context, batchKey *string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPendingBatchMinDeliverAfter, batchKey)
	var deliver_after pgtype.Timestamptz
	err := row.Scan(&deliver_after)
	return deliver_after, err
}

const listDueBatchKeys = `-- name: ListDueBatchKeys :many
SELECT DISTINCT batch_key
FROM notification_outbox
WHERE sent_at IS NULL
  AND batch_key IS NOT NULL
  AND deliver_after <= now()
ORDER BY batch_key
LIMIT $1
`

func (q *Queries) ListDueBatchKeys(ctx context.Context, limit int32) ([]*string, error) {
	rows, err := q.db.Query(ctx, listDueBatchKeys, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var batch_key *string
		if err := rows.Scan(&batch_key); err != nil {
			return nil, err
		}
		items = append(items, batch_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueBatchKeysForUser = `-- name: ListDueBatchKeysForUser :many
SELECT DISTINCT batch_key
FROM notification_outbox
WHERE user_id = $1
  AND sent_at IS NULL
  AND batch_key IS NOT NULL
  AND deliver_after <= now()
ORDER BY batch_key
`

func (q *Queries) ListDueBatchKeysForUser(ctx context.Context, userID pgtype.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listDueBatchKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var batch_key *string
		if err := rows.Scan(&batch_key); err != nil {
			return nil, err
		}
		items = append(items, batch_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueInstantOutbox = `-- name: ListDueInstantOutbox :many
SELECT id, user_id, category, title, body, data, batch_key, deliver_after, sent_at, read_at, created_at
FROM notification_outbox
WHERE sent_at IS NULL
  AND batch_key IS NULL
  AND deliver_after <= now()
ORDER BY deliver_after, created_at
LIMIT $1
`

func (q *Queries) ListDueInstantOutbox(ctx context.Context, limit int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listDueInstantOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.BatchKey,
			&i.DeliverAfter,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, category, title, body, data, batch_key, deliver_after, sent_at, read_at, created_at
FROM notification_outbox
WHERE user_id = $1
  AND sent_at IS NOT NULL
  AND (
    $2::timestamptz IS NULL
    OR sent_at < $2::timestamptz
    OR (sent_at = $2::timestamptz AND id < $3::uuid)
  )
ORDER BY sent_at DESC, id DESC
LIMIT $4
`

type ListNotificationsForUserParams struct {
	UserID       pgtype.UUID
	CursorSentAt pgtype.Timestamptz
	CursorID     pgtype.UUID
	PageLimit    int32
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.UserID,
		arg.CursorSentAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.BatchKey,
			&i.DeliverAfter,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingBatchRows = `-- name: ListPendingBatchRows :many
SELECT id, user_id, category, title, body, data, batch_key, deliver_after, sent_at, read_at, created_at
FROM notification_outbox
WHERE batch_key = $1
  AND sent_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPendingBatchRows(ctx context.Context, batchKey *string) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingBatchRows, batchKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.BatchKey,
			&i.DeliverAfter,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notification_outbox
SET read_at = now()
WHERE user_id = $1
  AND sent_at IS NOT NULL
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notification_outbox
SET read_at = now()
WHERE id = $1
  AND user_id = $2
  AND sent_at IS NOT NULL
  AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE notification_outbox
SET sent_at = now()
WHERE id = $1 AND sent_at IS NULL
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}

const markOutboxSentMany = `-- name: MarkOutboxSentMany :exec
UPDATE notification_outbox
SET sent_at = now()
WHERE id = ANY($1::uuid[])
  AND sent_at IS NULL
`

func (q *Queries) MarkOutboxSentMany(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxSentMany, dollar_1)
	return err
}

const updateOutboxContent = `-- name: UpdateOutboxContent :exec
UPDATE notification_outbox
SET title = $2, body = $3, data = $4
WHERE id = $1
`

type UpdateOutboxContentParams struct {
	ID    pgtype.UUID
	Title string
	Body  string
	Data  json.RawMessage
}

func (q *Queries) UpdateOutboxContent(ctx context.Context, arg UpdateOutboxContentParams) error {
	_, err := q.db.Exec(ctx, updateOutboxContent,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const upsertNotificationPref = `-- name: UpsertNotificationPref :exec
INSERT INTO notification_prefs (user_id, category, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, category) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertNotificationPrefParams struct {
	UserID   pgtype.UUID
	Category string
	Enabled  bool
}

func (q *Queries) UpsertNotificationPref(ctx context.Context, arg UpsertNotificationPrefParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPref, arg.UserID, arg.Category, arg.Enabled)
	return err
}
