// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (email, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code_hash, purpose, attempts, expires_at, consumed_at, created_at
`

type CreateOTPParams struct {
	Email     string
	CodeHash  string
	Purpose   string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Email,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOTPs = `-- name: DeleteOTPs :exec
DELETE FROM otp_codes WHERE email = $1 AND purpose = $2
`

type DeleteOTPsParams struct {
	Email   string
	Purpose string
}

func (q *Queries) DeleteOTPs(ctx context.Context, arg DeleteOTPsParams) error {
	_, err := q.db.Exec(ctx, deleteOTPs, arg.Email, arg.Purpose)
	return err
}

const getActiveOTP = `-- name: GetActiveOTP :one
SELECT id, email, code_hash, purpose, attempts, expires_at, consumed_at, created_at FROM otp_codes
WHERE email = $1 AND purpose = $2 AND consumed_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPParams struct {
	Email   string
	Purpose string
}

func (q *Queries) GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTP, arg.Email, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
