// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE user_id = $1 AND expo_token = $2
`

type DeletePushTokenParams struct {
	UserID    pgtype.UUID
	ExpoToken string
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.UserID, arg.ExpoToken)
	return err
}

const deletePushTokensForUser = `-- name: DeletePushTokensForUser :exec
DELETE FROM push_tokens WHERE user_id = $1
`

func (q *Queries) DeletePushTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePushTokensForUser, userID)
	return err
}

const listPushTokensForUser = `-- name: ListPushTokensForUser :many
SELECT expo_token, platform
FROM push_tokens
WHERE user_id = $1
`

type ListPushTokensForUserRow struct {
	ExpoToken string
	Platform  string
}

func (q *Queries) ListPushTokensForUser(ctx context.Context, userID pgtype.UUID) ([]ListPushTokensForUserRow, error) {
	rows, err := q.db.Query(ctx, listPushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushTokensForUserRow
	for rows.Next() {
		var i ListPushTokensForUserRow
		if err := rows.Scan(&i.ExpoToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetPushEligibleTokens = `-- name: ListWidgetPushEligibleTokens :many
SELECT expo_token
FROM push_tokens
WHERE user_id = $1
  AND (widget_push_at IS NULL OR widget_push_at < now() - interval '15 minutes')
`

func (q *Queries) ListWidgetPushEligibleTokens(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listWidgetPushEligibleTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var expo_token string
		if err := rows.Scan(&expo_token); err != nil {
			return nil, err
		}
		items = append(items, expo_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWidgetPushAt = `-- name: TouchWidgetPushAt :exec
UPDATE push_tokens
SET widget_push_at = now()
WHERE user_id = $1 AND expo_token = ANY($2::text[])
`

type TouchWidgetPushAtParams struct {
	UserID  pgtype.UUID
	Column2 []string
}

func (q *Queries) TouchWidgetPushAt(ctx context.Context, arg TouchWidgetPushAtParams) error {
	_, err := q.db.Exec(ctx, touchWidgetPushAt, arg.UserID, arg.Column2)
	return err
}

const upsertPushToken = `-- name: UpsertPushToken :exec
INSERT INTO push_tokens (user_id, expo_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, expo_token) DO UPDATE SET platform = $3, updated_at = now()
`

type UpsertPushTokenParams struct {
	UserID    pgtype.UUID
	ExpoToken string
	Platform  string
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPushToken, arg.UserID, arg.ExpoToken, arg.Platform)
	return err
}
