// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, device_name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token_hash, device_name, created_at, expires_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash string
	DeviceName       string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, refreshTokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, device_name, created_at, expires_at FROM sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE sessions
SET refresh_token_hash = $2, expires_at = $3
WHERE id = $1
`

type RotateSessionParams struct {
	ID               pgtype.UUID
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.ID, arg.RefreshTokenHash, arg.ExpiresAt)
	return err
}
