// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlbumsJoined = `-- name: CountAlbumsJoined :one
SELECT COUNT(*)::bigint AS count
FROM album_members
WHERE user_id = $1 AND invite_status = 'accepted'
`

func (q *Queries) CountAlbumsJoined(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbumsJoined, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCapsulesJoined = `-- name: CountCapsulesJoined :one
SELECT COUNT(*)::bigint AS count
FROM capsule_members
WHERE user_id = $1 AND invite_status = 'accepted'
`

func (q *Queries) CountCapsulesJoined(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCapsulesJoined, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMemoriesByKind = `-- name: CountUserMemoriesByKind :one
SELECT COUNT(*)::bigint AS total,
       COUNT(*) FILTER (WHERE med.kind = 'photo')::bigint AS photos,
       COUNT(*) FILTER (WHERE med.kind = 'video')::bigint AS videos,
       COUNT(*) FILTER (WHERE m.voice_media_id IS NOT NULL)::bigint AS voice_notes
FROM memories m
JOIN media med ON med.id = m.media_id
WHERE m.author_id = $1 AND m.deleted_at IS NULL
`

type CountUserMemoriesByKindRow struct {
	Total      int64
	Photos     int64
	Videos     int64
	VoiceNotes int64
}

func (q *Queries) CountUserMemoriesByKind(ctx context.Context, authorID pgtype.UUID) (CountUserMemoriesByKindRow, error) {
	row := q.db.QueryRow(ctx, countUserMemoriesByKind, authorID)
	var i CountUserMemoriesByKindRow
	err := row.Scan(
		&i.Total,
		&i.Photos,
		&i.Videos,
		&i.VoiceNotes,
	)
	return i, err
}

const heatmapAlbumContributions = `-- name: HeatmapAlbumContributions :many
SELECT (m.created_at AT TIME ZONE $2::text)::date AS day,
       COUNT(*)::bigint AS count
FROM memories m
WHERE m.author_id = $1
  AND m.container_type = 'album'
  AND m.deleted_at IS NULL
  AND m.created_at >= $3::timestamptz
  AND m.created_at < $4::timestamptz
GROUP BY day
ORDER BY day
`

type HeatmapAlbumContributionsParams struct {
	AuthorID pgtype.UUID
	Tz       string
	FromTs   pgtype.Timestamptz
	ToTs     pgtype.Timestamptz
}

type HeatmapAlbumContributionsRow struct {
	Day   pgtype.Date
	Count int64
}

func (q *Queries) HeatmapAlbumContributions(ctx context.Context, arg HeatmapAlbumContributionsParams) ([]HeatmapAlbumContributionsRow, error) {
	rows, err := q.db.Query(ctx, heatmapAlbumContributions,
		arg.AuthorID,
		arg.Tz,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeatmapAlbumContributionsRow
	for rows.Next() {
		var i HeatmapAlbumContributionsRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heatmapCapsuleContributions = `-- name: HeatmapCapsuleContributions :many
SELECT sd.day::date AS day,
       COUNT(*)::bigint AS count
FROM streak_days sd
JOIN capsule_members cm ON cm.capsule_id = sd.capsule_id
JOIN memories m ON m.container_type = 'capsule'
  AND m.container_id = sd.capsule_id
  AND m.author_id = $1
  AND m.deleted_at IS NULL
  AND (m.created_at AT TIME ZONE $2::text)::date = sd.day
WHERE cm.user_id = $1
  AND cm.invite_status = 'accepted'
  AND sd.day >= $3::date
  AND sd.day <= $4::date
GROUP BY sd.day
ORDER BY sd.day
`

type HeatmapCapsuleContributionsParams struct {
	AuthorID pgtype.UUID
	Tz       string
	FromDay  pgtype.Date
	ToDay    pgtype.Date
}

type HeatmapCapsuleContributionsRow struct {
	Day   pgtype.Date
	Count int64
}

func (q *Queries) HeatmapCapsuleContributions(ctx context.Context, arg HeatmapCapsuleContributionsParams) ([]HeatmapCapsuleContributionsRow, error) {
	rows, err := q.db.Query(ctx, heatmapCapsuleContributions,
		arg.AuthorID,
		arg.Tz,
		arg.FromDay,
		arg.ToDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeatmapCapsuleContributionsRow
	for rows.Next() {
		var i HeatmapCapsuleContributionsRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mostActiveMonth = `-- name: MostActiveMonth :one
SELECT to_char(date_trunc('month', m.created_at AT TIME ZONE $2::text), 'YYYY-MM') AS month,
       COUNT(*)::bigint AS count
FROM memories m
WHERE m.author_id = $1 AND m.deleted_at IS NULL
GROUP BY month
ORDER BY count DESC, month DESC
LIMIT 1
`

type MostActiveMonthParams struct {
	AuthorID pgtype.UUID
	Tz       string
}

type MostActiveMonthRow struct {
	Month string
	Count int64
}

func (q *Queries) MostActiveMonth(ctx context.Context, arg MostActiveMonthParams) (MostActiveMonthRow, error) {
	row := q.db.QueryRow(ctx, mostActiveMonth, arg.AuthorID, arg.Tz)
	var i MostActiveMonthRow
	err := row.Scan(&i.Month, &i.Count)
	return i, err
}
