// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionEventByRCID = `-- name: GetSubscriptionEventByRCID :one
SELECT id, user_id, revenuecat_event_id, event_type, plan, raw, created_at FROM subscription_events WHERE revenuecat_event_id = $1
`

func (q *Queries) GetSubscriptionEventByRCID(ctx context.Context, revenuecatEventID string) (SubscriptionEvent, error) {
	row := q.db.QueryRow(ctx, getSubscriptionEventByRCID, revenuecatEventID)
	var i SubscriptionEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatEventID,
		&i.EventType,
		&i.Plan,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const insertSubscriptionEvent = `-- name: InsertSubscriptionEvent :one
INSERT INTO subscription_events (user_id, revenuecat_event_id, event_type, plan, raw)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (revenuecat_event_id) DO NOTHING
RETURNING id, user_id, revenuecat_event_id, event_type, plan, raw, created_at
`

type InsertSubscriptionEventParams struct {
	UserID            pgtype.UUID
	RevenuecatEventID string
	EventType         string
	Plan              string
	Raw               json.RawMessage
}

func (q *Queries) InsertSubscriptionEvent(ctx context.Context, arg InsertSubscriptionEventParams) (SubscriptionEvent, error) {
	row := q.db.QueryRow(ctx, insertSubscriptionEvent,
		arg.UserID,
		arg.RevenuecatEventID,
		arg.EventType,
		arg.Plan,
		arg.Raw,
	)
	var i SubscriptionEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RevenuecatEventID,
		&i.EventType,
		&i.Plan,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}
