// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, display_name, password_hash, timezone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	DisplayName  string
	PasswordHash string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const emailTaken = `-- name: EmailTaken :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE email = $1 AND deleted_at IS NULL
) AS taken
`

func (q *Queries) EmailTaken(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailTaken, email)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const retireUsername = `-- name: RetireUsername :exec
INSERT INTO retired_usernames (username)
VALUES ($1)
ON CONFLICT (username) DO NOTHING
`

func (q *Queries) RetireUsername(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, retireUsername, username)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users
SET plan = $2,
    plan_expires_at = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at
`

type UpdateUserPlanParams struct {
	ID            pgtype.UUID
	Plan          string
	PlanExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPlan, arg.ID, arg.Plan, arg.PlanExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($2, display_name),
    timezone     = COALESCE($3, timezone)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, username, display_name, password_hash, avatar_media_id, timezone, plan, plan_expires_at, created_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID
	DisplayName *string
	Timezone    *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarMediaID,
		&i.Timezone,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const usernameTaken = `-- name: UsernameTaken :one
SELECT (
    EXISTS (SELECT 1 FROM users u WHERE u.username = $1 AND u.deleted_at IS NULL)
    OR EXISTS (SELECT 1 FROM retired_usernames r WHERE r.username = $1)
) AS taken
`

func (q *Queries) UsernameTaken(ctx context.Context, username string) (*bool, error) {
	row := q.db.QueryRow(ctx, usernameTaken, username)
	var taken *bool
	err := row.Scan(&taken)
	return taken, err
}
