// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: widget.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWidgetAlbumPhotos = `-- name: ListWidgetAlbumPhotos :many
SELECT DISTINCT ON (a.id)
       m.id AS memory_id,
       a.id AS album_id,
       a.name AS album_name,
       med.thumb_bucket_key,
       med.bucket_key AS media_key,
       med.kind AS media_kind
FROM albums a
JOIN album_members am ON am.album_id = a.id AND am.user_id = $1
JOIN memories m ON m.container_id = a.id AND m.container_type = 'album'
JOIN media med ON med.id = m.media_id
WHERE am.invite_status = 'accepted'
  AND am.left_at IS NULL
  AND a.state = 'active'
  AND m.deleted_at IS NULL
  AND med.status = 'ready'
ORDER BY a.id, m.created_at DESC
`

type ListWidgetAlbumPhotosRow struct {
	MemoryID       pgtype.UUID
	AlbumID        pgtype.UUID
	AlbumName      string
	ThumbBucketKey *string
	MediaKey       string
	MediaKind      string
}

func (q *Queries) ListWidgetAlbumPhotos(ctx context.Context, userID pgtype.UUID) ([]ListWidgetAlbumPhotosRow, error) {
	rows, err := q.db.Query(ctx, listWidgetAlbumPhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWidgetAlbumPhotosRow
	for rows.Next() {
		var i ListWidgetAlbumPhotosRow
		if err := rows.Scan(
			&i.MemoryID,
			&i.AlbumID,
			&i.AlbumName,
			&i.ThumbBucketKey,
			&i.MediaKey,
			&i.MediaKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetCapsuleCountdowns = `-- name: ListWidgetCapsuleCountdowns :many
SELECT c.id AS capsule_id, c.name AS capsule_name, c.unlock_at
FROM capsules c
JOIN capsule_members cm ON cm.capsule_id = c.id AND cm.user_id = $1
WHERE cm.invite_status = 'accepted'
  AND c.state IN ('pending', 'active', 'frozen')
ORDER BY c.unlock_at
`

type ListWidgetCapsuleCountdownsRow struct {
	CapsuleID   pgtype.UUID
	CapsuleName string
	UnlockAt    pgtype.Timestamptz
}

func (q *Queries) ListWidgetCapsuleCountdowns(ctx context.Context, userID pgtype.UUID) ([]ListWidgetCapsuleCountdownsRow, error) {
	rows, err := q.db.Query(ctx, listWidgetCapsuleCountdowns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWidgetCapsuleCountdownsRow
	for rows.Next() {
		var i ListWidgetCapsuleCountdownsRow
		if err := rows.Scan(&i.CapsuleID, &i.CapsuleName, &i.UnlockAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetUnlockedTodayMemories = `-- name: ListWidgetUnlockedTodayMemories :many
SELECT DISTINCT ON (c.id)
       m.id AS memory_id,
       c.id AS capsule_id,
       c.name AS capsule_name,
       med.thumb_bucket_key,
       med.bucket_key AS media_key,
       med.kind AS media_kind
FROM users u
JOIN capsule_members cm ON cm.user_id = u.id
JOIN capsules c ON c.id = cm.capsule_id
JOIN memories m ON m.container_id = c.id AND m.container_type = 'capsule'
JOIN media med ON med.id = m.media_id
WHERE u.id = $1
  AND cm.invite_status = 'accepted'
  AND cm.view_blocked = false
  AND c.state = 'unlocked'
  AND (c.viewable_until IS NULL OR c.viewable_until > now())
  AND c.unlocked_at IS NOT NULL
  AND c.unlocked_at >= ((now() AT TIME ZONE u.timezone)::date AT TIME ZONE u.timezone)
  AND c.unlocked_at < (((now() AT TIME ZONE u.timezone)::date + 1) AT TIME ZONE u.timezone)
  AND m.deleted_at IS NULL
  AND med.status = 'ready'
ORDER BY c.id, m.created_at DESC
`

type ListWidgetUnlockedTodayMemoriesRow struct {
	MemoryID       pgtype.UUID
	CapsuleID      pgtype.UUID
	CapsuleName    string
	ThumbBucketKey *string
	MediaKey       string
	MediaKind      string
}

func (q *Queries) ListWidgetUnlockedTodayMemories(ctx context.Context, id pgtype.UUID) ([]ListWidgetUnlockedTodayMemoriesRow, error) {
	rows, err := q.db.Query(ctx, listWidgetUnlockedTodayMemories, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWidgetUnlockedTodayMemoriesRow
	for rows.Next() {
		var i ListWidgetUnlockedTodayMemoriesRow
		if err := rows.Scan(
			&i.MemoryID,
			&i.CapsuleID,
			&i.CapsuleName,
			&i.ThumbBucketKey,
			&i.MediaKey,
			&i.MediaKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
